export const AnimalGame = [
  {
    jumbledWords: ['क', 'र्ण', 'र्', 'ण', 'ज', 'लो', 'ल', 'का', 'क'],
    correctWord: ['क', 'र्ण', 'ज', 'लो', 'का'],
    englishHint: '(It is five alphabet word)',
    sanskritHint: 'पञ्च अक्षर शब्द',
    word: 'Centipede',
    image: require('../../assets/animals/Centipede.png'),
  },
  {
    jumbledWords: ['ख', 'ड्.', 'ड्', 'गी', 'ग', 'गि'],
    correctWord: ['ख', 'ड्.', 'गी'],
    englishHint: '(It is three alphabet word)',
    sanskritHint: 'त्रि अक्षर शब्द',
    word: 'Rhinoceros',
    image: require('../../assets/animals/Rhinoceros.png'),
  },
  {
    jumbledWords: ['उ', 'ष्‍', 'ट्', 'र', 'ष्‍ट्र'],
    correctWord: ['उ', 'ष्‍ट्र'],
    englishHint: '(It is two alphabet word)',
    sanskritHint: 'द्वे अक्षर शब्द',
    word: 'Camel',
    image: require('../../assets/animals/Camel.png'),
  },
  {
    jumbledWords: ['श', 'स', 'स', 'ष', 'ष', 'श', 'कः'],
    correctWord: ['श', 'श', 'कः'],
    englishHint: '(It is three alphabet word)',
    sanskritHint: 'त्रि अक्षर शब्द',
    word: 'Rabbit',
    image: require('../../assets/animals/Rabbit.png'),
  },
  {
    jumbledWords: ['चि', 'चि', 'क्रो', 'क्', 'रो ', 'डः'],
    correctWord: ['चि', 'क्रो', 'डः'],
    englishHint: '(It is three alphabet word)',
    sanskritHint: 'त्रि अक्षर शब्द',
    word: 'Squirrel',
    image: require('../../assets/animals/Squirrel.png'),
  },
  {
    jumbledWords: ['ज', 'ला', 'श्‍वः'],
    correctWord: ['ज', 'ला', , 'ला', 'श्‍वः', 'श्‍', 'वः'],
    englishHint: '(It is three alphabet word)',
    sanskritHint: 'त्रि अक्षर शब्द',
    word: 'Hippopotamus',
    image: require('../../assets/animals/Hippopotamus.png'),
  },
  {
    jumbledWords: ['मा', 'म', 'र्जा', 'र्', 'जा', 'रः'],
    correctWord: ['मा', 'र्जा', 'रः'],
    englishHint: '(It is three alphabet word)',
    sanskritHint: 'त्रि अक्षर शब्द',
    word: 'cat',
    image: require('../../assets/animals/cat.png'),
  },
  {
    jumbledWords: ['त', 'र', 'क्षुः', 'क्षु', 'ट'],
    correctWord: ['त', 'र', 'क्षुः'],
    englishHint: '(It is three alphabet word)',
    sanskritHint: 'त्रि अक्षर शब्द',
    word: 'Cheetah',
    image: require('../../assets/animals/Cheetah.png'),
  },
  {
    jumbledWords: ['कृ', 'क', 'का', 'ला', 'ल', 'सः'],
    correctWord: ['कृ', 'क', 'ला', 'सः'],
    englishHint: '(It is four alphabet word)',
    sanskritHint: 'चत्वारि अक्षर शब्द',
    word: 'Chameleon',
    image: require('../../assets/animals/Chameleon.png'),
  },
  {
    jumbledWords: ['उ', 'र्ण', 'र्', 'ण ', 'ना', 'न', 'भः'],
    correctWord: ['उ', 'र्ण', 'ना', 'भः'],
    englishHint: '(It is four alphabet word)',
    sanskritHint: 'चत्वारि अक्षर शब्द',
    word: 'Spider',
    image: require('../../assets/animals/Spider.png'),
  },
  {
    jumbledWords: ['मू', 'मु', 'स', 'ष', 'कः'],
    correctWord: ['मू', 'ष', 'कः'],
    englishHint: '(It is three alphabet word)',
    sanskritHint: 'त्रि अक्षर शब्द',
    word: 'rat',
    image: require('../../assets/animals/rat.png'),
  },
  {
    jumbledWords: ['कु', 'क्कु', 'क्', 'कू', 'कु', 'रः'],
    correctWord: ['कु', 'क्कु', 'रः'],
    englishHint: '(It is three alphabet word)',
    sanskritHint: 'त्रि अक्षर शब्द',
    word: 'dog',
    image: require('../../assets/animals/dog.png'),
  },
  {
    jumbledWords: ['धे', 'नुः', 'नू:', 'णु:'],
    correctWord: ['धे', 'नुः'],
    englishHint: '(It is two alphabet word)',
    sanskritHint: 'द्वे अक्षर शब्द',
    word: 'cow',
    image: require('../../assets/animals/cow.png'),
  },
  {
    jumbledWords: ['शृ', 'श', 'गा', 'ग', 'लः', 'ल'],
    correctWord: ['शृ', 'गा', 'लः'],
    englishHint: '(It is three alphabet word)',
    sanskritHint: 'त्रि अक्षर शब्द',
    word: 'Jackal',
    image: require('../../assets/animals/Jackal.png'),
  },
  {
    jumbledWords: ['भ', 'ल्लू', 'ल्', 'लू', 'कः', 'क'],
    correctWord: ['भ', 'ल्लू', 'कः'],
    englishHint: '(It is three alphabet word)',
    sanskritHint: 'त्रि अक्षर शब्द',
    word: 'Bear',
    image: require('../../assets/animals/Bear.png'),
  },
  {
    jumbledWords: ['भ', 'ल्लू', 'ल्', 'लू', 'कः', 'क'],
    correctWord: ['भ', 'ल्लू', 'कः'],
    englishHint: '(It is three alphabet word)',
    sanskritHint: 'त्रि अक्षर शब्द',
    word: 'Crocodile',
    image: require('../../assets/animals/Crocodile.png'),
  },
  {
    jumbledWords: ['मे', 'मै', 'षः', 'ष', 'स:'],
    correctWord: ['मे', 'षः'],
    englishHint: '(It is two alphabet word)',
    sanskritHint: 'द्वे अक्षर शब्द',
    word: 'Sheep',
    image: require('../../assets/animals/Sheep.png'),
  },
  {
    jumbledWords: ['कं', 'क', 'गा', 'ग', 'रुः', 'रुः'],
    correctWord: ['कं', 'गा', 'रुः'],
    englishHint: '(It is three alphabet word)',
    sanskritHint: 'त्रि अक्षर शब्द',
    word: 'Kangaroo',
    image: require('../../assets/animals/Kangaroo.png'),
  },
  {
    jumbledWords: ['ख', 'खा', 'रः', 'र'],
    correctWord: ['ख', 'रः'],
    englishHint: '(It is two alphabet word)',
    sanskritHint: 'द्वे अक्षर शब्द',
    word: 'Donkey',
    image: require('../../assets/animals/Donkey.png'),
  },
  {
    jumbledWords: ['भे', 'भै', 'का:', 'कः'],
    correctWord: ['ख', 'रः'],
    englishHint: '(It is two alphabet word)',
    sanskritHint: 'द्वे अक्षर शब्द',
    word: 'Frog',
    image: require('../../assets/animals/Frog.png'),
  },
  {
    jumbledWords: ['अ', 'न', 'ना', 'डु', 'डू', 'ह'],
    correctWord: ['अ', 'न', 'डु', 'ह'],
    englishHint: '(It is four alphabet word)',
    sanskritHint: 'चत्वारि अक्षर शब्द',
    word: 'Bull',
    image: require('../../assets/animals/Bull.png'),
  },
  {
    jumbledWords: ['मी', 'नः', 'मि', 'न', 'ना:'],
    correctWord: ['मी', 'नः'],
    englishHint: '(It is two alphabet word)',
    sanskritHint: 'द्वे अक्षर शब्द',
    word: 'fish',
    image: require('../../assets/animals/fish.png'),
  },
  {
    jumbledWords: ['वा', 'व', 'न', 'ना:', 'रः', 'र'],
    correctWord: ['वा', 'न', 'रः'],
    englishHint: '(It is three alphabet word)',
    sanskritHint: 'त्रि अक्षर शब्द',
    word: 'Monkey',
    image: require('../../assets/animals/Monkey.png'),
  },
  {
    jumbledWords: ['गृ', 'ग', 'ह', 'गो', 'ग', 'धि', 'धी', 'का', 'क'],
    correctWord: ['गृ', 'ह', 'गो', 'धि', 'का'],
    englishHint: '(It is five alphabet word)',
    sanskritHint: 'पञ्च अक्षर शब्द',
    word: 'Lizard',
    image: require('../../assets/animals/Lizard.png'),
  },
  {
    jumbledWords: ['म', 'हि', 'षी', 'ष', 'ही', 'सि'],
    correctWord: ['म', 'हि', 'षी'],
    englishHint: '(It is three alphabet word)',
    sanskritHint: 'त्रि अक्षर शब्द',
    word: 'Buffalo',
    image: require('../../assets/animals/Buffalo.png'),
  },
  {
    jumbledWords: ['सू', 'क', 'रः', 'सु', 'स', 'र'],
    correctWord: ['सू', 'क', 'रः'],
    englishHint: '(It is three alphabet word)',
    sanskritHint: 'त्रि अक्षर शब्द',
    word: 'pig',
    image: require('../../assets/animals/pig.png'),
  },
  {
    jumbledWords: ['चि', 'ची', 'त्रो', 'त्र', 'ष्‍ट्र', 'ष्‍', 'ट्', 'र'],
    correctWord: ['चि', 'त्रो', 'ष्‍ट्र'],
    englishHint: '(It is three alphabet word)',
    sanskritHint: 'त्रि अक्षर शब्द',
    word: 'Giraffe',
    image: require('../../assets/animals/Giraffe.png'),
  },
  {
    jumbledWords: ['वृ', 'व', 'कः', 'क', 'का:'],
    correctWord: ['वृ', 'कः'],
    englishHint: '(It is two alphabet word)',
    sanskritHint: 'द्वे अक्षर शब्द',
    word: 'wolf',
    image: require('../../assets/animals/wolf.png'),
  },
  {
    jumbledWords: ['मृ', 'म', 'गः', 'ग', 'गा', 'गा:'],
    correctWord: ['मृ', 'गः'],
    englishHint: '(It is two alphabet word)',
    sanskritHint: 'द्वे अक्षर शब्द',
    word: 'deer',
    image: require('../../assets/animals/deer.png'),
  },
  {
    jumbledWords: ['अ', 'श्‍वः', 'श्‍', 'वः', 'व'],
    correctWord: ['अ', 'श्‍वः'],
    englishHint: '(It is two alphabet word)',
    sanskritHint: 'द्वे अक्षर शब्द',
    word: 'deer',
    image: require('../../assets/animals/deer.png'),
  },
  {
    jumbledWords: ['द्वी', 'द्', 'वी', 'पि', 'पी', 'न्'],
    correctWord: ['द्वी', 'पि', 'न्'],
    englishHint: '(It is three alphabet word)',
    sanskritHint: 'त्रि अक्षर शब्द',
    word: 'Tiger',
    image: require('../../assets/animals/Tiger.png'),
  },
  {
    jumbledWords: ['कु', 'कू', 'लि', 'ली', 'रः', 'र'],
    correctWord: ['कु', 'ली', 'रः'],
    englishHint: '(It is three alphabet word)',
    sanskritHint: 'त्रि अक्षर शब्द',
    word: 'crab',
    image: require('../../assets/animals/crab.png'),
  },
  {
    jumbledWords: ['ग', 'गा', 'जा', 'जा:', 'जः'],
    correctWord: ['ग', 'जः'],
    englishHint: '(It is two alphabet word)',
    sanskritHint: 'द्वे अक्षर शब्द',
    word: 'Elephant',
    image: require('../../assets/animals/Elephant.png'),
  },
  {
    jumbledWords: ['सिं', 'सी', 'हः', 'ह'],
    correctWord: ['सिं', 'हः'],
    englishHint: '(It is two alphabet word)',
    sanskritHint: 'द्वे अक्षर शब्द',
    word: 'Lion',
    image: require('../../assets/animals/Lion.png'),
  },
  {
    jumbledWords: ['त', 'ता', 'र', 'क्षुः', 'रा', 'क्षु'],
    correctWord: ['त', 'र', 'क्षुः'],
    englishHint: '(It is three alphabet word)',
    sanskritHint: 'त्रि अक्षर शब्द',
    word: 'Leopard',
    image: require('../../assets/animals/Leopard.png'),
  },
  {
    jumbledWords: ['क', 'च्‍छ', 'च्‍', 'का', 'छ', 'प'],
    correctWord: ['क', 'च्‍छ', 'प'],
    englishHint: '(It is three alphabet word)',
    sanskritHint: 'त्रि अक्षर शब्द',
    word: 'Tortoise',
    image: require('../../assets/animals/Tortoise.png'),
  },
  {
    jumbledWords: ['अ', 'आ', 'जा', 'ज'],
    correctWord: ['अ', 'जा'],
    englishHint: '(It is two alphabet word)',
    sanskritHint: 'द्वे अक्षर शब्द',
    word: 'Goat',
    image: require('../../assets/animals/Goat.png'),
  },
];
