export const BirdGame = [
  {
    jumbledWords: ['म', 'यू', 'मा', 'यु', 'रः'],
    correctWord: ['म', 'यू', 'रः'],
    englishHint: '(It is three alphabet word)',
    sanskritHint: 'त्रि अक्षर शब्द',
    word: 'Peacock',
    image: require('../../assets/birds/Peacock.png'),
  },
  {
    jumbledWords: ['क', 'पो', 'तः', 'पौ', 'ता', 'ता:'],
    correctWord: ['क', 'पो', 'तः'],
    englishHint: '(It is three alphabet word)',
    sanskritHint: 'त्रि अक्षर शब्द',
    word: 'Dove',
    image: require('../../assets/birds/Dove.png'),
  },
  {
    jumbledWords: ['शु', 'सू', 'सु', 'कः', 'क'],
    correctWord: ['शु', 'कः'],
    englishHint: '(It is two alphabet word)',
    sanskritHint: 'द्वे अक्षर शब्द',
    word: 'Parrot',
    image: require('../../assets/birds/Parrot.png'),
  },
  {
    jumbledWords: ['ग', 'रु', 'र', 'णः', 'ण', 'ना:'],
    correctWord: ['ग', 'रु', 'णः'],
    englishHint: '(It is three alphabet word)',
    sanskritHint: 'त्रि अक्षर शब्द',
    word: 'Eagle',
    image: require('../../assets/birds/Eagle.png'),
  },
  {
    jumbledWords: ['सा', 'स', 'शा', 'र', 'सः', 'स'],
    correctWord: ['ग', 'रु', 'णः'],
    englishHint: '(It is three alphabet word)',
    sanskritHint: 'त्रि अक्षर शब्द',
    word: 'Stork',
    image: require('../../assets/birds/stork.png'),
  },
  {
    jumbledWords: ['टि', 'ट्टि', 'ट्', 'भी:', 'टी', 'टि', 'भिः'],
    correctWord: ['टि', 'ट्टि', 'भिः'],
    englishHint: '(It is three alphabet word)',
    sanskritHint: 'त्रि अक्षर शब्द',
    word: 'Lapwing',
    image: require('../../assets/birds/lapwing.png'),
  },
  {
    jumbledWords: ['दा', 'द', 'र्वा', 'र्व', 'घा', 'घ', 'टः', 'ट'],
    correctWord: ['दा', 'र्वा', 'घा', 'टः'],
    englishHint: '(It is three alphabet word)',
    sanskritHint: 'त्रि अक्षर शब्द',
    word: 'Woodpecker',
    image: require('../../assets/birds/Woodpecker.png'),
  },
  {
    jumbledWords: ['उ', 'ष्‍ट्र', 'ष्‍', 'ट्', 'र', 'प', 'क्षी', 'क्ष'],
    correctWord: ['उ', 'ष्‍ट्र', 'प', 'क्षी'],
    englishHint: '(It is four alphabet word)',
    sanskritHint: 'चत्वारि अक्षर शब्द',
    word: 'Ostrich',
    image: require('../../assets/birds/Ostrich.png'),
  },
  {
    jumbledWords: ['हं', 'ह', 'सः', 'स', 'सा:'],
    correctWord: ['हं', 'सः'],
    englishHint: '(It is two alphabet word)',
    sanskritHint: 'द्वे अक्षर शब्द',
    word: 'swan',
    image: require('../../assets/birds/swan.png'),
  },
  {
    jumbledWords: ['सा', 'स', 'रि', 'का', 'का:', 'क:', 'री'],
    correctWord: ['सा', 'रि', 'का'],
    englishHint: '(It is three alphabet word)',
    sanskritHint: 'त्रि अक्षर शब्द',
    word: 'Myna',
    image: require('../../assets/birds/Myna.png'),
  },
  {
    jumbledWords: ['का', 'क', 'द', 'म्‍बः', 'म्‍', 'दा', 'बः'],
    correctWord: ['का', 'द', 'म्‍बः'],
    englishHint: '(It is three alphabet word)',
    sanskritHint: 'त्रि अक्षर शब्द',
    word: 'Duck',
    image: require('../../assets/birds/Duck.png'),
  },
  {
    jumbledWords: ['च', 'चा', 'ट', 'टा', 'कः', 'का'],
    correctWord: ['च', 'ट', 'कः'],
    englishHint: '(It is three alphabet word)',
    sanskritHint: 'त्रि अक्षर शब्द',
    word: 'Sparrow',
    image: require('../../assets/birds/Sparrow.png'),
  },
  {
    jumbledWords: ['ष', 'ट्', 'ट', 'प', 'दः', 'स', 'सा:'],
    correctWord: ['ष', 'ट्', 'प', 'दः'],
    englishHint: '(It is four alphabet word)',
    sanskritHint: 'चत्वारि अक्षर शब्द',
    word: 'BumbleBee',
    image: require('../../assets/birds/BumbleBee.png'),
  },
  {
    jumbledWords: ['च', 'क्र', 'क्', 'र', 'वा', 'व', 'कः', 'क'],
    correctWord: ['च', 'क्र', 'वा', 'कः'],
    englishHint: '(It is four alphabet word)',
    sanskritHint: 'चत्वारि अक्षर शब्द',
    word: 'Skylark',
    image: require('../../assets/birds/Skylark.png'),
  },
  {
    jumbledWords: ['ब', 'कः', 'क', 'का:', 'का'],
    correctWord: ['ब', 'कः'],
    englishHint: '(It is two alphabet word)',
    sanskritHint: 'द्वे अक्षर शब्द',
    word: 'Heron',
    image: require('../../assets/birds/Heron.png'),
  },
  {
    jumbledWords: ['उ', 'लू', 'कः', 'लु', 'ल', 'का:', 'का'],
    correctWord: ['उ', 'लू', 'कः'],
    englishHint: '(It is three alphabet word)',
    sanskritHint: 'त्रि अक्षर शब्द',
    word: 'Owl',
    image: require('../../assets/birds/Owl.png'),
  },
  {
    jumbledWords: ['क', 'का', 'पाे', 'पौ', 'तः', 'त'],
    correctWord: ['क', 'पाे', 'तः'],
    englishHint: '(It is three alphabet word)',
    sanskritHint: 'त्रि अक्षर शब्द',
    word: 'Pigeon',
    image: require('../../assets/birds/Pigeon.png'),
  },
  {
    jumbledWords: ['नी', 'ल', 'क', 'ण्‍ठः', 'ण्‍', 'ठः', 'नि'],
    correctWord: ['नी', 'ल', 'क', 'ण्‍ठः'],
    englishHint: '(It is four alphabet word)',
    sanskritHint: 'चत्वारि अक्षर शब्द',
    word: 'Kingfisher',
    image: require('../../assets/birds/kingfisher.png'),
  },
  {
    jumbledWords: ['ज', 'तु', 'का:', 'का', 'तू', 'कः'],
    correctWord: ['ज', 'तु', 'का'],
    englishHint: '(It is three alphabet word)',
    sanskritHint: 'त्रि अक्षर शब्द',
    word: 'Bat',
    image: require('../../assets/birds/Bat.png'),
  },
  {
    jumbledWords: ['व', 'र्त', 'र्', 'त', 'कः', 'का:', 'का'],
    correctWord: ['व', 'र्त', 'कः'],
    englishHint: '(It is three alphabet word)',
    sanskritHint: 'त्रि अक्षर शब्द',
    word: 'Quail',
    image: require('../../assets/birds/Quail.png'),
  },
  {
    jumbledWords: ['का', 'कः', 'का:', 'का', 'क'],
    correctWord: ['का', 'कः'],
    englishHint: '(It is two alphabet word)',
    sanskritHint: 'द्वे अक्षर शब्द',
    word: 'Crow',
    image: require('../../assets/birds/crow.png'),
  },
  {
    jumbledWords: ['चा', 'च', 'त', 'कः', 'का:', 'का', 'क'],
    correctWord: ['चा', 'त', 'कः'],
    englishHint: '(It is three alphabet word)',
    sanskritHint: 'त्रि अक्षर शब्द',
    word: 'Cuckoo',
    image: require('../../assets/birds/Cuckoo.png'),
  },
  {
    jumbledWords: ['चा', 'च', 'को', 'रा:', 'रः', 'र'],
    correctWord: ['च', 'को', 'रः'],
    englishHint: '(It is three alphabet word)',
    sanskritHint: 'त्रि अक्षर शब्द',
    word: 'Ptarmigan',
    image: require('../../assets/birds/Ptarmigan.png'),
  },
  {
    jumbledWords: ['व', 'रा:', 'रः', 'र', 'टा', 'ट', 'टा:'],
    correctWord: ['व', 'र', 'टा'],
    englishHint: '(It is three alphabet word)',
    sanskritHint: 'त्रि अक्षर शब्द',
    word: 'Goose',
    image: require('../../assets/birds/Goose.png'),
  },
  {
    jumbledWords: ['स', 'ला', 'सा', 'श', 'ल', 'भः', 'भ'],
    correctWord: ['श', 'ल', 'भः'],
    englishHint: '(It is three alphabet word)',
    sanskritHint: 'त्रि अक्षर शब्द',
    word: 'Kite',
    image: require('../../assets/birds/Kite.png'),
  },
  {
    jumbledWords: ['को', 'को', 'कि', 'लः', 'ल', 'की'],
    correctWord: ['को', 'कि', 'लः'],
    englishHint: '(It is three alphabet word)',
    sanskritHint: 'त्रि अक्षर शब्द',
    word: 'Nightingale',
    image: require('../../assets/birds/Nightingale.png'),
  },
  {
    jumbledWords: ['कु', 'कू', 'क्‍कु', 'क्‍', 'कु', 'टः'],
    correctWord: ['कु', 'क्‍कु', 'टः'],
    englishHint: '(It is three alphabet word)',
    sanskritHint: 'त्रि अक्षर शब्द',
    word: 'Cock',
    image: require('../../assets/birds/Cock.png'),
  },
  {
    jumbledWords: ['गृ', 'ग', 'ध्', 'रः', 'ध्रः'],
    correctWord: ['गृ', 'ध्रः'],
    englishHint: '(It is two alphabet word)',
    sanskritHint: 'द्वे अक्षर शब्द',
    word: 'Vulture',
    image: require('../../assets/birds/Vulture.png'),
  },
];
