export const FruitGame = [
  {
    jumbledWords: ['ज', 'आ', 'म्र', 'म्', 'म्‍'],
    correctWord: ['आ', 'म्र', 'म्'],
    englishHint: '(It is three alphabet word)',
    sanskritHint: 'त्रि अक्षर शब्द',
    word: 'mango',
    image: require('../../assets/fruits/mango.png'),
  },
  {
    jumbledWords: ['म्र', 'ज', 'से', 'ब', 'फ', 'ल', 'म्', 'आ'],
    correctWord: ['से', 'ब', 'फ', 'ल', 'म्'],
    englishHint: '(It is five alphabet word)',
    sanskritHint: 'पञ्च अक्षर शब्द',
    image: require('../../assets/fruits/apple.png'),
    word: 'apple',
  },
  {
    jumbledWords: ['प्र', 'ल', 'य', 'लु', 'या', 'प्रि'],
    correctWord: ['प्रि', 'या', 'लु'],
    englishHint: '(It is three alphabet word)',
    image: require('../../assets/fruits/Apricot.png'),
    sanskritHint: 'त्रि अक्षर शब्द',
    word: 'Apricot',
  },
  {
    jumbledWords: ['ल', 'क', 'म्र', 'ली', 'ल', 'फ', 'द', 'म्', 'म'],
    correctWord: ['क', 'द', 'ली', 'फ', 'ल', 'म्'],
    image: require('../../assets/fruits/banana.png'),
    englishHint: '(It is six alphabet word)',
    sanskritHint: 'षट् अक्षर शब्द',
    word: 'banana',
  },
  {
    jumbledWords: ['म्', 'बु', 'ल', 'ज', 'म', 'म्र', 'ब', 'ल', 'फ', 'म्'],
    correctWord: ['ज', 'म्', 'बु', 'फ', 'ल', 'म्'],
    englishHint: '(It is six alphabet word)',
    image: require('../../assets/fruits/blackberry.png'),
    sanskritHint: 'षट् अक्षर शब्द',
    word: 'Blackberries',
  },
  {
    jumbledWords: ['ब', 'नी', 'री', 'न', 'ली', 'ल', 'द', 'र'],
    correctWord: ['नी', 'ल', 'ब', 'द', 'री'],
    englishHint: '(It is five alphabet word)',
    image: require('../../assets/fruits/blueberry.png'),
    sanskritHint: 'पञ्च अक्षर शब्द',
    word: 'Blueberries',
  },
  {
    jumbledWords: ['क', 'र्द', 'र', 'म', 'द', 'र्', 'क:', 'म्'],
    correctWord: ['क', 'र', 'म', 'र्द', 'क:'],
    englishHint: '(It is five alphabet word)',
    image: require('../../assets/fruits/carnberry.png'),
    sanskritHint: 'पञ्च अक्षर शब्द',
    word: 'Cranberry',
  },
  {
    jumbledWords: ['र्बू', 'ख', 'ज', 'र्ब', 'र्'],
    correctWord: ['ख', 'र्बू', 'ज'],
    image: require('../../assets/fruits/Cantaloupe.png'),
    englishHint: '(It is three alphabet word)',
    sanskritHint: 'त्रि अक्षर शब्द',
    word: 'Cantaloupe',
  },
  {
    jumbledWords: ['र', 'प', 'र', 'प्', 'द', 'र्', 'ब'],
    correctWord: ['प्', 'र', 'ब', 'द', 'र'],
    englishHint: '(It is five alphabet word)',
    image: require('../../assets/fruits/cherry.png'),
    sanskritHint: 'पञ्च अक्षर शब्द',
    word: 'Cherries',
  },
  {
    jumbledWords: ['के', 'न', 'रि', 'म्', 'र', 'ना', 'क', 'ल', 'म'],
    correctWord: ['ना', 'रि', 'के', 'ल', 'म्'],
    englishHint: '(It is five alphabet word)',
    image: require('../../assets/fruits/Coconut.png'),
    sanskritHint: 'पञ्च अक्षर शब्द',
    word: 'Coconut',
  },
  {
    image: require('../../assets/fruits/corn.png'),
    jumbledWords: ['क्षि', 'क्ष', 'री', 'स्', 'व', 'र्ण', 'र्', 'स्व'],
    correctWord: ['स्व', 'र्ण', 'क्षि', 'री'],
    englishHint: '(It is four alphabet word)',
    sanskritHint: 'चत्वारि अक्षर शब्द',
    word: 'Corn',
  },
  {
    jumbledWords: ['र्', 'क', 'री', 'ट', 'र्क', 'का'],
    image: require('../../assets/fruits/Cucumbers.png'),
    correctWord: ['क', 'र्क', 'टी', 'का'],
    englishHint: '(It is four alphabet word)',
    sanskritHint: 'चत्वारि अक्षर शब्द',
    word: 'Cucumbers',
  },
  {
    jumbledWords: ['फ', 'स', 'त', 'ल', 'म्', 'म', 'सी'],
    correctWord: ['सी', 'त', 'फ', 'ल', 'म्'],
    englishHint: '(It is five alphabet word)',
    sanskritHint: 'पञ्च अक्षर शब्द',
    image: require('../../assets/fruits/CustardApple.png'),
    word: 'Custard_Apple',
  },
  {
    jumbledWords: ['र', 'म्', 'फ', 'ख', 'ज', 'ल', 'जू', 'म'],
    correctWord: ['ख', 'जू', 'र', 'फ', 'ल', 'म्'],
    englishHint: '(It is six alphabet word)',
    image: require('../../assets/fruits/dates.png'),
    sanskritHint: 'षट् अक्षर शब्द',
    word: 'dates',
  },
  {
    jumbledWords: ['म्ब', 'उ', 'द', 'दु', 'म', 'र', 'म्', 'ब'],
    correctWord: ['उ', 'दु', 'म्ब', 'र', 'म्'],
    englishHint: '(It is five alphabet word)',
    sanskritHint: 'पञ्च अक्षर शब्द',
    word: 'Fig',
    image: require('../../assets/fruits/fig.png'),
  },
  {
    jumbledWords: ['क', 'आ', 'म्', 'ल', 'म्ल', 'कि'],
    correctWord: ['आ', 'म्ल', 'कि'],
    englishHint: '(It is three alphabet word)',
    sanskritHint: 'त्रि अक्षर शब्द',
    word: 'gooseberry',
    image: require('../../assets/fruits/gooseberry.png'),
  },
  {
    jumbledWords: ['द्र', 'ल', 'क्षा', 'क्ष', 'द्रा', 'फ', 'म्', 'क्षा', 'म'],
    correctWord: ['द्रा', 'क्षा', 'फ', 'ल', 'म्'],
    englishHint: '(It is five alphabet word)',
    sanskritHint: 'पञ्च अक्षर शब्द',
    image: require('../../assets/fruits/grapes.png'),
    word: 'Grapes',
  },
  {
    jumbledWords: ['ग', 'ग्', 'ग्र', 'ल', 'आ', 'म्', 'म'],
    correctWord: ['आ', 'ग्र', 'ल', 'म्'],
    englishHint: '(It is four alphabet word)',
    image: require('../../assets/fruits/guava.png'),
    sanskritHint: 'चत्वारि अक्षर शब्द',
    word: 'Guava',
  },
  {
    jumbledWords: ['न', 'स', 'प', 'ना', 'म्', 'म'],
    correctWord: ['प', 'न', 'स', 'म्'],
    englishHint: '(It is four alphabet word)',
    sanskritHint: 'चत्वारि अक्षर शब्द',
    image: require('../../assets/fruits/jackfruit.png'),
    word: 'Jackfruit',
  },
  {
    jumbledWords: ['द', 'र', 'ब', 'फ', 'ल', 'म्', 'री', 'म'],
    correctWord: ['ब', 'द', 'री', 'फ', 'ल', 'म्'],
    englishHint: '(It is six alphabet word)',
    sanskritHint: 'षट् अक्षर शब्द',
    word: 'Jujube',
    image: require('../../assets/fruits/Jujube.png'),
  },
  {
    jumbledWords: ['म', 'ज', 'ब', 'म्‍', 'र', 'बी', 'म्'],
    correctWord: ['ज', 'म्‍', 'बी', 'र', 'म्'],
    englishHint: '(It is five alphabet word)',
    image: require('../../assets/fruits/lemon.png'),
    sanskritHint: 'पञ्च अक्षर शब्द',
    word: 'lemon',
  },
  {
    jumbledWords: ['क', 'ली', 'च', 'ल', 'का', 'चि'],
    correctWord: ['ली', 'चि', 'का'],
    englishHint: '(It is three alphabet word)',
    sanskritHint: 'त्रि अक्षर शब्द',
    image: require('../../assets/fruits/lychee.png'),
    word: 'Lychee',
  },
  {
    jumbledWords: ['त', 'ल', 'म्', 'द', 'फ', 'म', 'तू'],
    correctWord: ['तू', 'द', 'फ', 'ल', 'म्'],
    englishHint: '(It is five alphabet word)',
    sanskritHint: 'पञ्च अक्षर शब्द',
    image: require('../../assets/fruits/Mulberry.png'),
    word: 'Mulberry',
  },
  {
    jumbledWords: ['वि', 'क', 'म्', 'त', 'व', 'कू', 'म'],
    image: require('../../assets/fruits/Naseberry.png'),
    correctWord: ['वि', 'कू', 'त', 'म्'],
    englishHint: '(It is four alphabet word)',
    sanskritHint: 'चत्वारि अक्षर शब्द',
    word: 'Naseberry',
  },
  {
    jumbledWords: ['रं', 'म्', 'न', 'र', 'ना', 'ग', 'म'],
    correctWord: ['ना', 'रं', 'ग', 'म्'],
    englishHint: '(It is four alphabet word)',
    sanskritHint: 'चत्वारि अक्षर शब्द',
    image: require('../../assets/fruits/orange.png'),
    word: 'Orange',
  },
  {
    jumbledWords: ['टी', 'ध', 'क', 'र्क', 'धु', 'र्', 'म', 'ट'],
    correctWord: ['म', 'धु', 'क', 'र्क', 'टी'],
    englishHint: '(It is five alphabet word)',
    sanskritHint: 'पञ्च अक्षर शब्द',
    image: require('../../assets/fruits/papaya.png'),
    word: 'Papaya',
  },
  {
    jumbledWords: ['द्र', 'अ', 'ल', 'आ', 'लु:', 'द्रा', 'लु'],
    correctWord: ['आ', 'द्रा', 'लु:'],
    englishHint: '(It is three alphabet word)',
    sanskritHint: 'त्रि अक्षर शब्द',
    image: require('../../assets/fruits/Peach.png'),
    word: 'Peach',
  },
  {
    jumbledWords: ['आ', 'म्', 'फ', 'म', 'त', 'ल', 'अ', 'मृ', 'म'],
    correctWord: ['अ', 'मृ', 'त', 'फ', 'ल', 'म्'],
    englishHint: '(It is three alphabet word)',
    image: require('../../assets/fruits/Pear.png'),
    sanskritHint: 'त्रि अक्षर शब्द',
    word: 'Pear',
  },
  {
    jumbledWords: ['ना', 'न', 'अ', 'म्', 'म', 'आ', 'न', 'ना', 'स'],
    correctWord: ['अ', 'ना', 'ना', 'स', 'म्'],
    englishHint: '(It is five alphabet word)',
    sanskritHint: 'पञ्च अक्षर शब्द',
    image: require('../../assets/fruits/Pineapple.png'),
    word: 'Pineapple',
  },
  {
    jumbledWords: ['क', 'अ', 'म्', 'ल', 'आ', 'म', 'को'],
    correctWord: ['अ', 'को', 'ल', 'म्'],
    englishHint: '(It is four alphabet word)',
    image: require('../../assets/fruits/Pistachio.png'),
    sanskritHint: 'चत्वारि अक्षर शब्द',
    word: 'Pistachio',
  },
  {
    jumbledWords: ['द', 'दा', 'ड', 'म', 'डि', 'म्'],
    correctWord: ['दा', 'डि', 'म', 'म्'],
    englishHint: '(It is four alphabet word)',
    image: require('../../assets/fruits/pomogranate.png'),
    sanskritHint: 'चत्वारि अक्षर शब्द',
    word: 'pomegranate',
  },
  {
    jumbledWords: ['शु', 'क्षा', 'ष्', 'क', 'श', 'द्रा', 'ष्क', 'क्ष'],
    correctWord: ['शु', 'ष्क', 'द्रा', 'क्षा'],
    englishHint: '(It is four alphabet word)',
    image: require('../../assets/fruits/rasin.png'),
    sanskritHint: 'चत्वारि अक्षर शब्द',
    word: 'Rasins',
  },
  {
    jumbledWords: ['ब', 'तृ', 'द', 'ण', 'त', 'र', 'न'],
    correctWord: ['तृ', 'ण', 'ब', 'द', 'र'],
    englishHint: '(It is five alphabet word)',
    image: require('../../assets/fruits/strawberry.png'),
    sanskritHint: 'पञ्च अक्षर शब्द',
    word: 'Strawberry',
  },
  {
    jumbledWords: ['इ', 'क्', 'क्षु', 'षु'],
    correctWord: ['इ', 'क्षु'],
    englishHint: '(It is two alphabet word)',
    image: require('../../assets/fruits/sugarcane.png'),
    sanskritHint: 'द्वे अक्षर शब्द',
    word: 'Sugarcane',
  },
  {
    jumbledWords: ['म', 'ष्टा', 'मि', 'ष्ट', 'ल', 'क', 'म्', 'लु'],
    correctWord: ['मि', 'ष्टा', 'लु', 'क', 'म्'],
    englishHint: '(It is five alphabet word)',
    image: require('../../assets/fruits/sweetPotato.png'),
    sanskritHint: 'पञ्च अक्षर शब्द',
    word: 'Sweet_Potato',
  },
  {
    jumbledWords: ['कः', 'रक्', 'रक्ता', 'रक्त', 'ङ्', 'ङ्ग'],
    correctWord: ['रक्ता', 'ङ्ग', 'कः'],
    englishHint: '(It is three alphabet word)',
    image: require('../../assets/fruits/tomato.png'),
    sanskritHint: 'त्रि अक्षर शब्द',
    word: 'Tomato',
  },
  {
    jumbledWords: ['अ', 'क्ष', 'क्षो', 'क्', 'ट', 'म'],
    correctWord: ['अ', 'क्षो', 'ट', 'म'],
    englishHint: '(It is four alphabet word)',
    image: require('../../assets/fruits/walnut.png'),
    sanskritHint: 'चत्वारि अक्षर शब्द',
    word: 'Walnut',
  },
  {
    jumbledWords: ['क', 'गा', 'ड', 'श्र', 'श्रृ', 'ट', 'ड्', 'ग'],
    correctWord: ['श्रृ', 'ड्', 'गा', 'ट', 'क'],
    englishHint: '(It is five alphabet word)',
    sanskritHint: 'पञ्च अक्षर शब्द',
    image: require('../../assets/fruits/waterchestnut.png'),
    word: 'Water_Chestnut',
  },
  {
    jumbledWords: ['लि', 'क', 'म्', 'ल', 'द', 'म', 'लिं'],
    correctWord: ['क', 'लिं', 'द', 'म्'],
    englishHint: '(It is four alphabet word)',
    sanskritHint: 'चत्वारि अक्षर शब्द',
    image: require('../../assets/fruits/watermelon.png'),
    word: 'Watermelon',
  },
  {
    jumbledWords: ['ति', 'म्', 'डी', 'त', 'तिं', 'ड', 'क', 'म'],
    correctWord: ['तिं', 'त', 'डी', 'क', 'म्'],
    englishHint: '(It is five alphabet word)',
    image: require('../../assets/fruits/tarmarind.png'),
    sanskritHint: 'पञ्च अक्षर शब्द',
    word: 'Tamarind',
  },
];
