export const NumbersGame = [
  {
    jumbledWords: ['शू', 'न्य', 'सु', 'सू', 'न्यः', 'शु'],
    correctWord: ['शू', 'न्य'],
    englishHint: '(It is two alphabet word)',
    sanskritHint: 'द्वे अक्षर शब्द',
    word: 'zero',
    number: '0',
  },
  {
    jumbledWords: ['ए', 'क', 'म्', 'का', 'के', 'म्', 'म:'],
    correctWord: ['ए', 'क', 'म्'],
    englishHint: '(It is three alphabet word)',
    sanskritHint: 'त्रि अक्षर शब्द',
    word: 'one',
    number: '1',
  },
  {
    jumbledWords: ['द्वे', 'द्व', 'द्वे:', 'द्', 'वे'],
    correctWord: ['द्वे'],
    englishHint: '(It is one alphabet word)',
    sanskritHint: 'एकम् अक्षर शब्द',
    word: 'two',
    number: '2',
  },
  {
    jumbledWords: ['त्री', 'णि', 'त्', 'री', 'ण', 'त्र', 'णि:'],
    correctWord: ['त्री', 'णि'],
    englishHint: '(It is two alphabet word)',
    sanskritHint: 'द्वे अक्षर शब्द',
    word: 'three',
    number: '3',
  },
  {
    jumbledWords: ['च', 'चा', 'त्वा', 'त्', 'वा', 'रि', 'री', 'री:'],
    correctWord: ['च', 'त्वा', 'रि'],
    englishHint: '(It is three alphabet word)',
    sanskritHint: 'त्रि अक्षर शब्द',
    word: 'four',
    number: '4',
  },
  {
    jumbledWords: ['प', 'ञ्च', 'ञ्च:', 'पा', 'ञ्', 'च'],
    correctWord: ['प', 'ञ्च'],
    englishHint: '(It is two alphabet word)',
    sanskritHint: 'द्वे अक्षर शब्द',
    word: 'five',
    number: '5',
  },
  {
    jumbledWords: ['ष', 'ट्', 'ट', 'स', 'श', 'ट्:'],
    correctWord: ['ष', 'ट्'],
    englishHint: '(It is two alphabet word)',
    sanskritHint: 'द्वे अक्षर शब्द',
    word: 'six',
    number: '6',
  },
  {
    jumbledWords: ['स', 'ष', 'श', 'प्त', 'प्त:', 'प्', 'त'],
    correctWord: ['स', 'प्त'],
    englishHint: '(It is two alphabet word)',
    sanskritHint: 'द्वे अक्षर शब्द',
    word: 'seven',
    number: '7',
  },
  {
    jumbledWords: ['अ', 'ष्ट', 'ष्', 'ष्ट:', 'ट', 'आ'],
    correctWord: ['अ', 'ष्ट'],
    englishHint: '(It is two alphabet word)',
    sanskritHint: 'द्वे अक्षर शब्द',
    word: 'eight',
    number: '8',
  },
  {
    jumbledWords: ['न', 'व', 'व:', 'ना'],
    correctWord: ['न', 'व'],
    englishHint: '(It is two alphabet word)',
    sanskritHint: 'द्वे अक्षर शब्द',
    word: 'nine',
    number: '9',
  },
  {
    jumbledWords: ['द', 'श', 'सा', 'स', 'श:', 'शा', 'षा'],
    correctWord: ['द', 'श'],
    englishHint: '(It is two alphabet word)',
    sanskritHint: 'द्वे अक्षर शब्द',
    word: 'ten',
    number: '10',
  },
  {
    jumbledWords: ['ए', 'का', 'क', 'द', 'श', 'सा', 'स', 'श:', 'शा', 'षा'],
    correctWord: ['ए', 'का', 'द', 'श'],
    englishHint: '(It is four alphabet word)',
    sanskritHint: 'चत्वारि अक्षर शब्द',
    word: 'eleven',
    number: '11',
  },
  {
    jumbledWords: ['द्वा', 'द्', 'वा', 'द', 'श', 'सा', 'स', 'श:', 'शा', 'षा'],
    correctWord: ['द्वा', 'द', 'श'],
    englishHint: '(It is three alphabet word)',
    sanskritHint: 'त्रि अक्षर शब्द',
    word: 'twelve',
    number: '12',
  },
  {
    jumbledWords: [
      'त्र',
      'यो',
      'त्',
      'र',
      'य',
      'द',
      'श',
      'सा',
      'स',
      'श:',
      'शा',
      'षा',
    ],
    correctWord: ['त्र', 'यो', 'द', 'श'],
    englishHint: '(It is four alphabet word)',
    sanskritHint: 'चत्वारि अक्षर शब्द',
    word: 'thirteen',
    number: '13',
  },
  {
    jumbledWords: [
      'च',
      'तु',
      'र्द',
      'र्',
      'द',
      'तू',
      'श',
      'सा',
      'स',
      'श:',
      'शा',
      'षा',
    ],
    correctWord: ['च', 'तु', 'र्द', 'श'],
    englishHint: '(It is four alphabet word)',
    sanskritHint: 'चत्वारि अक्षर शब्द',
    word: 'fourteen',
    number: '14',
  },
  {
    jumbledWords: [
      'प',
      'ञ्च',
      'ञ्',
      'च',
      'द',
      'श',
      'सा',
      'स',
      'श:',
      'शा',
      'षा',
    ],
    correctWord: ['प', 'ञ्च', 'द', 'श'],
    englishHint: '(It is four alphabet word)',
    sanskritHint: 'चत्वारि अक्षर शब्द',
    word: 'fifteen',
    number: '15',
  },
  {
    jumbledWords: ['षो', 'सो', 'शो', 'ड', 'श', 'श', 'स', 'श:', 'ष'],
    correctWord: ['षो', 'ड', 'श'],
    englishHint: '(It is three alphabet word)',
    sanskritHint: 'त्रि अक्षर शब्द',
    word: 'sixteen',
    number: '16',
  },
  {
    jumbledWords: [
      'स',
      'प्त',
      'प्',
      'त',
      'द',
      'श',
      'सा',
      'स',
      'श:',
      'शा',
      'षा',
    ],
    correctWord: ['स', 'प्त', 'द', 'श'],
    englishHint: '(It is four alphabet word)',
    sanskritHint: 'चत्वारि अक्षर शब्द',
    word: 'seventeen',
    number: '17',
  },
  {
    jumbledWords: [
      'अ',
      'ष्टा',
      'ष्',
      'टा',
      'द',
      'श',
      'सा',
      'स',
      'श:',
      'शा',
      'षा',
    ],
    correctWord: ['अ', 'ष्टा', 'द', 'श'],
    englishHint: '(It is four alphabet word)',
    sanskritHint: 'चत्वारि अक्षर शब्द',
    word: 'eighteen',
    number: '18',
  },
  {
    jumbledWords: ['न', 'व', 'व:', 'ना', 'द', 'श', 'सा', 'स', 'श:', 'शा', 'षा'],
    correctWord: ['न', 'व', 'द', 'श'],
    englishHint: '(It is four alphabet word)',
    sanskritHint: 'चत्वारि अक्षर शब्द',
    word: 'nineteen',
    number: '19',
  },
  {
    jumbledWords: ['विं', 'वी', 'वीं', 'श', 'तिः', 'ती:', 'ती'],
    correctWord: ['विं', 'श', 'तिः'],
    englishHint: '(It is three alphabet word)',
    sanskritHint: 'त्रि अक्षर शब्द',
    word: 'twenty',
    number: '20',
  },
  {
    jumbledWords: ['ए', 'क', 'का', 'विं', 'वी', 'वीं', 'श', 'तिः', 'ती:', 'ती'],
    correctWord: ['ए', 'क', 'विं', 'श', 'तिः'],
    englishHint: '(It is five alphabet word)',
    sanskritHint: 'पञ्च अक्षर शब्द',
    word: 'twentyone',
    number: '21',
  },
  {
    jumbledWords: [
      'द्वा',
      'द्व',
      'द्',
      'वा',
      'विं',
      'वी',
      'वीं',
      'श',
      'तिः',
      'ती:',
      'ती',
    ],
    correctWord: ['द्वा', 'विं', 'श', 'तिः'],
    englishHint: '(It is four alphabet word)',
    sanskritHint: 'चत्वारि अक्षर शब्द',
    word: 'twentytwo',
    number: '22',
  },
  {
    jumbledWords: [
      'त्र',
      'त्',
      'र',
      'यो',
      'विं',
      'वी',
      'वीं',
      'श',
      'तिः',
      'ती:',
      'ती',
    ],
    correctWord: ['त्र', 'यो', 'विं', 'श', 'तिः'],
    englishHint: '(It is five alphabet word)',
    sanskritHint: 'पञ्च अक्षर शब्द',
    word: 'twentythree',
    number: '23',
  },
  {
    jumbledWords: [
      'च',
      'तु',
      'तू',
      'र्विं',
      'विं',
      'वी',
      'वीं',
      'श',
      'तिः',
      'ती:',
      'ती',
    ],
    correctWord: ['च', 'तु', 'र्विं', 'श', 'तिः'],
    englishHint: '(It is five alphabet word)',
    sanskritHint: 'पञ्च अक्षर शब्द',
    word: 'twentyfour',
    number: '24',
  },
  {
    jumbledWords: [
      'प',
      'ञ्च',
      'ञ्',
      'च',
      'विं',
      'वी',
      'वीं',
      'श',
      'तिः',
      'ती:',
      'ती',
    ],
    correctWord: ['प', 'ञ्च', 'विं', 'श', 'तिः'],
    englishHint: '(It is five alphabet word)',
    sanskritHint: 'पञ्च अक्षर शब्द',
    word: 'twentyfive',
    number: '25',
  },

  {
    jumbledWords: [
      'ष',
      'ड्विं',
      'स',
      'श',
      'विं',
      'वी',
      'वीं',
      'श',
      'तिः',
      'ती:',
      'ती',
    ],
    correctWord: ['ष', 'ड्विं', 'श', 'तिः'],
    englishHint: '(It is five alphabet word)',
    sanskritHint: 'पञ्च अक्षर शब्द',
    word: 'twentysix',
    number: '26',
  },
  {
    jumbledWords: [
      'स',
      'प्त',
      'प्',
      'त',
      'विं',
      'वी',
      'वीं',
      'श',
      'तिः',
      'ती:',
      'ती',
    ],
    correctWord: ['स', 'प्त', 'विं', 'श', 'तिः'],
    englishHint: '(It is five alphabet word)',
    sanskritHint: 'पञ्च अक्षर शब्द',
    word: 'twentyseven',
    number: '27',
  },
  {
    jumbledWords: [
      'अ',
      'ष्टा',
      'ष्',
      'टा',
      'विं',
      'वी',
      'वीं',
      'श',
      'तिः',
      'ती:',
      'ती',
    ],
    correctWord: ['अ', 'ष्टा', 'विं', 'श', 'तिः'],
    englishHint: '(It is five alphabet word)',
    sanskritHint: 'पञ्च अक्षर शब्द',
    word: 'twentyeight',
    number: '28',
  },
  {
    jumbledWords: [
      'न',
      'व',
      'व:',
      'ना',
      'विं',
      'वी',
      'वीं',
      'श',
      'तिः',
      'ती:',
      'ती',
    ],
    correctWord: ['न', 'व', 'विं', 'श', 'तिः'],
    englishHint: '(It is five alphabet word)',
    sanskritHint: 'पञ्च अक्षर शब्द',
    word: 'twentynine',
    number: '29',
  },
  {
    jumbledWords: ['त्रिं', 'त्रि', 'स', 'त्री', 'श', 'त्', 'त', 'त्:'],
    correctWord: ['त्रिं', 'श', 'त्'],
    englishHint: '(It is three alphabet word)',
    sanskritHint: 'त्रि अक्षर शब्द',
    word: 'thirty',
    number: '30',
  },
  {
    jumbledWords: [
      'ए',
      'क',
      'म्',
      'का',
      'के',
      'त्रिं',
      'त्रि',
      'स',
      'त्री',
      'श',
      'त्',
      'त',
      'त्:',
    ],
    correctWord: ['ए', 'क', 'त्रिं', 'श', 'त्'],
    englishHint: '(It is five alphabet word)',
    sanskritHint: 'पञ्च अक्षर शब्द',
    word: 'thirtyone',
    number: '31',
  },
  {
    jumbledWords: [
      'द्वे',
      'द्व',
      'द्वे:',
      'द्',
      'वे',
      'त्रिं',
      'त्रि',
      'स',
      'त्री',
      'श',
      'त्',
      'त',
      'त्:',
    ],
    correctWord: ['द्वे', 'त्रिं', 'श', 'त्'],
    englishHint: '(It is four alphabet word)',
    sanskritHint: 'चत्वारि अक्षर शब्द',
    word: 'thirtytwo',
    number: '32',
  },
  {
    jumbledWords: [
      'त्र',
      'त्',
      'र',
      'य',
      'स्त्रिं',
      'स्त्',
      'रिं ',
      'श',
      'त्',
      'त्रिं',
      'त्रि',
      'स',
      'त्री',
      'त',
      'त्:',
    ],
    correctWord: ['त्र', 'य', 'स्त्रिं', 'श', 'त्'],
    englishHint: '(It is five alphabet word)',
    sanskritHint: 'पञ्च अक्षर शब्द',
    word: 'thirtythree',
    number: '33',
  },
  {
    jumbledWords: [
      'च',
      'तु',
      'तू',
      'स्त्रिं',
      'स्त्',
      'रिं ',
      'श',
      'त्',
      'त्रिं',
      'त्रि',
      'स',
      'त्री',
      'त',
      'त्:',
    ],
    correctWord: ['च', 'तु', 'स्त्रिं', 'श', 'त्'],
    englishHint: '(It is five alphabet word)',
    sanskritHint: 'पञ्च अक्षर शब्द',
    word: 'thirtythree',
    number: '34',
  },
  {
    jumbledWords: [
      'प',
      'ञ्च',
      'ञ्',
      'च',
      'त्रिं',
      'त्रि',
      'स',
      'त्री',
      'श',
      'त्',
      'त',
      'त्:',
    ],
    correctWord: ['प', 'ञ्च', 'त्रिं', 'श', 'त्'],
    englishHint: '(It is five alphabet word)',
    sanskritHint: 'पञ्च अक्षर शब्द',
    word: 'thirtyfive',
    number: '35',
  },
  {
    jumbledWords: [
      'ष',
      'ट्त्रिं',
      'ट्',
      'स',
      'श',
      'त्',
      'रिं',
      'स',
      'त्री',
      'श',
      'त्',
      'त',
      'त्:',
    ],
    correctWord: ['ष', 'ट्त्रिं', 'श', 'त्'],
    englishHint: '(It is four alphabet word)',
    sanskritHint: 'चत्वारि अक्षर शब्द',
    word: 'thirtysix',
    number: '36',
  },
  {
    jumbledWords: [
      'स',
      'प्त',
      'प्',
      'त',
      'त्रिं',
      'त्रि',
      'स',
      'त्री',
      'श',
      'त्',
      'त',
      'त्:',
    ],
    correctWord: ['स', 'प्त', 'त्रिं', 'श', 'त्'],
    englishHint: '(It is five alphabet word)',
    sanskritHint: 'पञ्च अक्षर शब्द',
    word: 'thirtyseven',
    number: '37',
  },
  {
    jumbledWords: [
      'अ',
      'ष्ट',
      'ष्',
      'ट',
      'त्रिं',
      'त्रि',
      'स',
      'त्री',
      'श',
      'त्',
      'त',
      'त्:',
    ],
    correctWord: ['अ', 'ष्ट', 'त्रिं', 'श', 'त्'],
    englishHint: '(It is five alphabet word)',
    sanskritHint: 'पञ्च अक्षर शब्द',
    word: 'thirtyeight',
    number: '38',
  },
  {
    jumbledWords: [
      'न',
      'व',
      'त्रिं',
      'त्रि',
      'स',
      'त्री',
      'श',
      'त्',
      'त',
      'त्:',
    ],
    correctWord: ['न', 'व', 'त्रिं', 'श', 'त्'],
    englishHint: '(It is five alphabet word)',
    sanskritHint: 'पञ्च अक्षर शब्द',
    word: 'thirtynine',
    number: '39',
  },
  {
    jumbledWords: ['च', 'त्वा', 'त्', 'वा', 'रिं', 'री', 'श', 'ष', 'स', 'त्'],
    correctWord: ['च', 'त्वा', 'रिं', 'श', 'त्'],
    englishHint: '(It is five alphabet word)',
    sanskritHint: 'पञ्च अक्षर शब्द',
    word: 'forty',
    number: '40',
  },
  {
    jumbledWords: [
      'ए',
      'क',
      'का',
      'च',
      'त्वा',
      'त्',
      'वा',
      'रिं',
      'री',
      'श',
      'ष',
      'स',
      'त्',
    ],
    correctWord: ['ए', 'क', 'च', 'त्वा', 'रिं', 'श', 'त्'],
    englishHint: '(It is seven alphabet word)',
    sanskritHint: 'सप्त अक्षर शब्द',
    word: 'fortyone',
    number: '41',
  },
  {
    jumbledWords: [
      'द्वा',
      'द्',
      'वा',
      'च',
      'त्वा',
      'त्',
      'वा',
      'रिं',
      'री',
      'श',
      'ष',
      'स',
      'त्',
    ],
    correctWord: ['द्वा', 'च', 'त्वा', 'रिं', 'श', 'त्'],
    englishHint: '(It is six alphabet word)',
    sanskritHint: 'षट् अक्षर शब्द',
    word: 'fortytwo',
    number: '42',
  },
  {
    jumbledWords: [
      'त्रि',
      'त्',
      'रि',
      'च',
      'त्वा',
      'त्',
      'वा',
      'रिं',
      'री',
      'श',
      'ष',
      'स',
      'त्',
    ],
    correctWord: ['त्रि', 'च', 'त्वा', 'रिं', 'श', 'त्'],
    englishHint: '(It is six alphabet word)',
    sanskritHint: 'षट् अक्षर शब्द',
    word: 'fortythree',
    number: '43',
  },
  {
    jumbledWords: [
      'च',
      'तु',
      'तू',
      'श्च',
      'श्',
      'च',
      'त्वा',
      'त्',
      'वा',
      'रिं',
      'रीं',
      'श',
      'त्',
      'स',
      'ष',
    ],
    correctWord: ['च', 'तु', 'श्च', 'त्वा', 'रिं', 'श', 'त्'],
    englishHint: '(It is seven alphabet word)',
    sanskritHint: 'सप्त अक्षर शब्द',
    word: 'fortyfour',
    number: '44',
  },

  {
    jumbledWords: [
      'प',
      'ञ्च',
      'ञ्',
      'च',
      'च',
      'त्वा',
      'त्',
      'वा',
      'रिं',
      'री',
      'श',
      'ष',
      'स',
      'त्',
    ],
    correctWord: ['प', 'ञ्च', 'च', 'त्वा', 'रिं', 'श', 'त्'],
    englishHint: '(It is seven alphabet word)',
    sanskritHint: 'सप्त अक्षर शब्द',
    word: 'fortyfive',
    number: '45',
  },
  {
    jumbledWords: [
      'ष',
      'ट्',
      'ट',
      'च',
      'त्वा',
      'त्',
      'वा',
      'रिं',
      'री',
      'श',
      'ष',
      'स',
      'त्',
    ],
    correctWord: ['ष', 'ट्', 'च', 'त्वा', 'रिं', 'श', 'त्'],
    englishHint: '(It is seven alphabet word)',
    sanskritHint: 'सप्त अक्षर शब्द',
    word: 'fortysix',
    number: '46',
  },
  {
    jumbledWords: [
      'स',
      'प्त',
      'प्',
      'त',
      'च',
      'त्वा',
      'त्',
      'वा',
      'रिं',
      'री',
      'श',
      'ष',
      'स',
      'त्',
    ],
    correctWord: ['स', 'प्त', 'च', 'त्वा', 'रिं', 'श', 'त्'],
    englishHint: '(It is seven alphabet word)',
    sanskritHint: 'सप्त अक्षर शब्द',
    word: 'fortyseven',
    number: '47',
  },
  {
    jumbledWords: [
      'अ',
      'आ',
      'ष्टा',
      'ष्',
      'टा',
      'च',
      'त्वा',
      'त्',
      'वा',
      'रिं',
      'री',
      'श',
      'ष',
      'स',
      'त्',
    ],
    correctWord: ['अ', 'ष्टा', 'च', 'त्वा', 'रिं', 'श', 'त्'],
    englishHint: '(It is seven alphabet word)',
    sanskritHint: 'सप्त अक्षर शब्द',
    word: 'fortyeight',
    number: '48',
  },
  {
    jumbledWords: [
      'न',
      'व',
      'व:',
      'ना',
      'च',
      'त्वा',
      'त्',
      'वा',
      'रिं',
      'री',
      'श',
      'ष',
      'स',
      'त्',
    ],
    correctWord: ['न', 'व', 'च', 'त्वा', 'रिं', 'श', 'त्'],
    englishHint: '(It is seven alphabet word)',
    sanskritHint: 'सप्त अक्षर शब्द',
    word: 'fortynine',
    number: '49',
  },
  {
    jumbledWords: ['प', 'ञ्चा', 'ञ्', 'स', 'चा', 'श', 'त्', 'त', 'त्:'],
    correctWord: ['प', 'ञ्चा', 'श', 'त्'],
    englishHint: '(It is four alphabet word)',
    sanskritHint: 'चत्वारि अक्षर शब्द',
    word: 'fifty',
    number: '50',
  },
  {
    jumbledWords: [
      'ए',
      'क',
      'का',
      'के',
      'प',
      'ञ्चा',
      'ञ्',
      'स',
      'चा',
      'श',
      'त्',
      'त',
      'त्:',
    ],
    correctWord: ['ए', 'क', 'प', 'ञ्चा', 'श', 'त्'],
    englishHint: '(It is six alphabet word)',
    sanskritHint: 'षट् अक्षर शब्द',
    word: 'fiftyone',
    number: '51',
  },
  {
    jumbledWords: [
      'द्वि',
      'द्',
      'वि',
      'प',
      'ञ्चा',
      'ञ्',
      'स',
      'चा',
      'श',
      'त्',
      'त',
      'त्:',
    ],
    correctWord: ['द्वि', 'प', 'ञ्चा', 'श', 'त्'],
    englishHint: '(It is five alphabet word)',
    sanskritHint: 'पञ्च अक्षर शब्द',
    word: 'fiftytwo',
    number: '52',
  },
  {
    jumbledWords: [
      'त्रि',
      'त्',
      'रि',
      'प',
      'ञ्चा',
      'ञ्',
      'स',
      'चा',
      'श',
      'त्',
      'त',
      'त्:',
    ],
    correctWord: ['त्रि', 'प', 'ञ्चा', 'श', 'त्'],
    englishHint: '(It is five alphabet word)',
    sanskritHint: 'पञ्च अक्षर शब्द',
    word: 'fiftythree',
    number: '53',
  },
  {
    jumbledWords: [
      'च',
      'तुः',
      'तू',
      'तू:',
      'प',
      'ञ्चा',
      'ञ्',
      'स',
      'चा',
      'श',
      'त्',
      'त',
      'त्:',
    ],
    correctWord: ['च', 'तुः', 'प', 'ञ्चा', 'श', 'त्'],
    englishHint: '(It is six alphabet word)',
    sanskritHint: 'षट् अक्षर शब्द',
    word: 'fiftyfour',
    number: '54',
  },
  {
    jumbledWords: [
      'प',
      'ञ्च',
      'ञ्च',
      'प',
      'ञ्चा',
      'ञ',
      'ञ्',
      'स',
      'चा',
      'श',
      'त्',
      'त',
      'त्:',
    ],
    correctWord: ['प', 'ञ्च', 'प', 'ञ्चा', 'श', 'त्'],
    englishHint: '(It is six alphabet word)',
    sanskritHint: 'षट् अक्षर शब्द',
    word: 'fiftyfive',
    number: '55',
  },
  {
    jumbledWords: [
      'ष',
      'ट्',
      'स',
      'श',
      'प',
      'ञ्चा',
      'ञ्',
      'स',
      'चा',
      'श',
      'त्',
      'त',
      'त्:',
    ],
    correctWord: ['ष', 'ट्', 'प', 'ञ्चा', 'श', 'त्'],
    englishHint: '(It is six alphabet word)',
    sanskritHint: 'षट् अक्षर शब्द',
    word: 'fiftysix',
    number: '56',
  },
  {
    jumbledWords: [
      'स',
      'प्त',
      'प्',
      'त',
      'प',
      'ञ्चा',
      'ञ्',
      'स',
      'चा',
      'श',
      'त्',
      'त',
      'त्:',
    ],
    correctWord: ['स', 'प्त', 'प', 'ञ्चा', 'श', 'त्'],
    englishHint: '(It is six alphabet word)',
    sanskritHint: 'षट् अक्षर शब्द',
    word: 'fiftyseven',
    number: '57',
  },
  {
    jumbledWords: [
      'अ',
      'ष्ट',
      'ष्',
      'आ',
      'ट',
      'प',
      'ञ्चा',
      'ञ्',
      'स',
      'चा',
      'श',
      'त्',
      'त',
      'त्:',
    ],
    correctWord: ['अ', 'ष्ट', 'प', 'ञ्चा', 'श', 'त्'],
    englishHint: '(It is six alphabet word)',
    sanskritHint: 'षट् अक्षर शब्द',
    word: 'fiftyeight',
    number: '58',
  },
  {
    jumbledWords: [
      'न',
      'व',
      'व:',
      'ना',
      'प',
      'ञ्चा',
      'ञ्',
      'स',
      'चा',
      'श',
      'त्',
      'त',
      'त्:',
    ],
    correctWord: ['न', 'व', 'प', 'ञ्चा', 'श', 'त्'],
    englishHint: '(It is six alphabet word)',
    sanskritHint: 'षट् अक्षर शब्द',
    word: 'fiftynine',
    number: '59',
  },
  {
    jumbledWords: ['ष', 'स', 'श', 'ष्टिः', 'ष्टि', 'ष्', 'टि'],
    correctWord: ['ष', 'ष्टिः'],
    englishHint: '(It is two alphabet word)',
    sanskritHint: 'द्वे अक्षर शब्द',
    word: 'sixty',
    number: '60',
  },
  {
    jumbledWords: ['ए', 'क', 'का', 'ष', 'स', 'श', 'ष्टिः', 'ष्टि', 'ष्', 'टि'],
    correctWord: ['ए', 'क', 'ष', 'ष्टिः'],
    englishHint: '(It is four alphabet word)',
    sanskritHint: 'चत्वारि अक्षर शब्द',
    word: 'sixtyone',
    number: '61',
  },
  {
    jumbledWords: [
      'द्वि',
      'द्',
      'वि',
      'ष',
      'स',
      'श',
      'ष्टिः',
      'ष्टि',
      'ष्',
      'टि',
    ],
    correctWord: ['द्वि', 'ष', 'ष्टिः'],
    englishHint: '(It is three alphabet word)',
    sanskritHint: 'त्रि अक्षर शब्द',
    word: 'sixtytwo',
    number: '62',
  },
  {
    jumbledWords: [
      'त्रि',
      'त्',
      'रि',
      'ष',
      'स',
      'श',
      'ष्टिः',
      'ष्टि',
      'ष्',
      'टि',
    ],
    correctWord: ['त्रि', 'ष', 'ष्टिः'],
    englishHint: '(It is three alphabet word)',
    sanskritHint: 'त्रि अक्षर शब्द',
    word: 'sixtythree',
    number: '63',
  },
  {
    jumbledWords: [
      'च',
      'तुः',
      'तू',
      'तू:',
      'ष',
      'स',
      'श',
      'ष्टिः',
      'ष्टि',
      'ष्',
      'टि',
    ],
    correctWord: ['च', 'तुः', 'ष', 'ष्टिः'],
    englishHint: '(It is four alphabet word)',
    sanskritHint: 'चत्वारि अक्षर शब्द',
    word: 'sixtyfour',
    number: '64',
  },
  {
    jumbledWords: [
      'प',
      'ञ्च',
      'ञ्च:',
      'पा',
      'ञ्',
      'च',
      'ष',
      'स',
      'श',
      'ष्टिः',
      'ष्टि',
      'ष्',
      'टि',
    ],
    correctWord: ['प', 'ञ्च', 'ष', 'ष्टिः'],
    englishHint: '(It is four alphabet word)',
    sanskritHint: 'चत्वारि अक्षर शब्द',
    word: 'sixtyfive',
    number: '65',
  },
  {
    jumbledWords: [
      'ष',
      'ट्',
      'ट',
      'स',
      'श',
      'ट्:',
      'ष',
      'स',
      'श',
      'ष्टिः',
      'ष्टि',
      'ष्',
      'टि',
    ],
    correctWord: ['ष', 'ट्', 'ष', 'ष्टिः'],
    englishHint: '(It is four alphabet word)',
    sanskritHint: 'चत्वारि अक्षर शब्द',
    word: 'sixtysix',
    number: '66',
  },
  {
    jumbledWords: [
      'स',
      'ष',
      'श',
      'प्त',
      'प्त:',
      'प्',
      'त',
      'ष',
      'स',
      'श',
      'ष्टिः',
      'ष्टि',
      'ष्',
      'टि',
    ],
    correctWord: ['स', 'प्त', 'ष', 'ष्टिः'],
    englishHint: '(It is four alphabet word)',
    sanskritHint: 'चत्वारि अक्षर शब्द',
    word: 'sixtyseven',
    number: '67',
  },
  {
    jumbledWords: [
      'अ',
      'ष्ट',
      'ष्',
      'ष्ट:',
      'ट',
      'आ',
      'ष',
      'स',
      'श',
      'ष्टिः',
      'ष्टि',
      'ष्',
      'टि',
    ],
    correctWord: ['अ', 'ष्ट', 'ष', 'ष्टिः'],
    englishHint: '(It is four alphabet word)',
    sanskritHint: 'चत्वारि अक्षर शब्द',
    word: 'sixtyeight',
    number: '68',
  },
  {
    jumbledWords: [
      'न',
      'व',
      'व:',
      'ना',
      'ष',
      'स',
      'श',
      'ष्टिः',
      'ष्टि',
      'ष्',
      'टि',
    ],
    correctWord: ['न', 'व', 'ष', 'ष्टिः'],
    englishHint: '(It is four alphabet word)',
    sanskritHint: 'चत्वारि अक्षर शब्द',
    word: 'sixtynine',
    number: '69',
  },
  {
    jumbledWords: ['स', 'श', 'ष', 'प्त', 'प्', 'त', 'तिः', 'ती:'],
    correctWord: ['स', 'प्त', 'तिः'],
    englishHint: '(It is three alphabet word)',
    sanskritHint: 'त्रि अक्षर शब्द',
    word: 'seventy',
    number: '70',
  },
  {
    jumbledWords: [
      'ए',
      'क',
      'का',
      'के',
      'स',
      'श',
      'ष',
      'प्त',
      'प्',
      'त',
      'तिः',
      'ती:',
    ],
    correctWord: ['ए', 'क', 'स', 'प्त', 'तिः'],
    englishHint: '(It is five alphabet word)',
    sanskritHint: 'पञ्च अक्षर शब्द',
    word: 'seventyone',
    number: '71',
  },
  {
    jumbledWords: [
      'द्वे',
      'द्व',
      'द्वे:',
      'द्',
      'वे',
      'स',
      'श',
      'ष',
      'प्त',
      'प्',
      'त',
      'तिः',
      'ती:',
    ],
    correctWord: ['द्वे', 'स', 'प्त', 'तिः'],
    englishHint: '(It is four alphabet word)',
    sanskritHint: 'चत्वारि अक्षर शब्द',
    word: 'seventytwo',
    number: '72',
  },
  {
    jumbledWords: [
      'त्री',
      'त्रि',
      'त्',
      'री',
      'त्र',
      'स',
      'श',
      'ष',
      'प्त',
      'प्',
      'त',
      'तिः',
      'ती:',
    ],
    correctWord: ['त्रि', 'स', 'प्त', 'तिः'],
    englishHint: '(It is four alphabet word)',
    sanskritHint: 'चत्वारि अक्षर शब्द',
    word: 'seventythree',
    number: '73',
  },
  {
    jumbledWords: [
      'च',
      'तू:',
      'तुः',
      'स',
      'श',
      'ष',
      'प्त',
      'प्',
      'त',
      'तिः',
      'ती:',
    ],
    correctWord: ['च', 'तू:', 'स', 'प्त', 'तिः'],
    englishHint: '(It is five alphabet word)',
    sanskritHint: 'पञ्च अक्षर शब्द',
    word: 'seventyfour',
    number: '74',
  },
  {
    jumbledWords: [
      'प',
      'ञ्च',
      'ञ्च:',
      'पा',
      'ञ्',
      'च',
      'स',
      'श',
      'ष',
      'प्त',
      'प्',
      'त',
      'तिः',
      'ती:',
    ],
    correctWord: ['प', 'ञ्च', 'स', 'प्त', 'तिः'],
    englishHint: '(It is five alphabet word)',
    sanskritHint: 'पञ्च अक्षर शब्द',
    word: 'seventyfive',
    number: '75',
  },
  {
    jumbledWords: [
      'ष',
      'ट्',
      'ट',
      'स',
      'श',
      'ट्:',
      'स',
      'श',
      'ष',
      'प्त',
      'प्',
      'त',
      'तिः',
      'ती:',
    ],
    correctWord: ['ष', 'ट्', 'स', 'प्त', 'तिः'],
    englishHint: '(It is five alphabet word)',
    sanskritHint: 'पञ्च अक्षर शब्द',
    word: 'seventysix',
    number: '76',
  },
  {
    jumbledWords: [
      'स',
      'ष',
      'श',
      'प्त',
      'प्त:',
      'प्',
      'त',
      'स',
      'श',
      'ष',
      'प्त',
      'प्',
      'त',
      'तिः',
      'ती:',
    ],
    correctWord: ['स', 'प्त', 'स', 'प्त', 'तिः'],
    englishHint: '(It is five alphabet word)',
    sanskritHint: 'पञ्च अक्षर शब्द',
    word: 'seventyseven',
    number: '77',
  },
  {
    jumbledWords: [
      'अ',
      'ष्ट',
      'ष्',
      'ष्ट:',
      'ट',
      'आ',
      'स',
      'श',
      'ष',
      'प्त',
      'प्',
      'त',
      'तिः',
      'ती:',
    ],
    correctWord: ['अ', 'ष्ट', 'स', 'प्त', 'तिः'],
    englishHint: '(It is five alphabet word)',
    sanskritHint: 'पञ्च अक्षर शब्द',
    word: 'seventyeight',
    number: '78',
  },
  {
    jumbledWords: [
      'न',
      'व',
      'व:',
      'ना',
      'स',
      'श',
      'ष',
      'प्त',
      'प्',
      'त',
      'तिः',
      'ती:',
    ],
    correctWord: ['न', 'व', 'स', 'प्त', 'तिः'],
    englishHint: '(It is five alphabet word)',
    sanskritHint: 'पञ्च अक्षर शब्द',
    word: 'seventynine',
    number: '79',
  },
  {
    jumbledWords: ['अ', 'शी', 'तिः', 'ति', 'शि', 'आ', 'ती', 'ती:'],
    correctWord: ['अ', 'शी', 'तिः'],
    englishHint: '(It is three alphabet word)',
    sanskritHint: 'त्रि अक्षर शब्द',
    word: 'eighty',
    number: '80',
  },
  {
    jumbledWords: ['ए', 'का', 'क', 'शी', 'तिः', 'ति', 'शि', 'ती', 'ती:'],
    correctWord: ['ए', 'का', 'शी', 'तिः'],
    englishHint: '(It is four alphabet word)',
    sanskritHint: 'चत्वारि अक्षर शब्द',
    word: 'eightyone',
    number: '81',
  },
  {
    jumbledWords: [
      'द्',
      'द',
      'व्य',
      'व्',
      'य',
      'शी',
      'तिः',
      'ति',
      'शि',
      'ती',
      'ती:',
    ],
    correctWord: ['द्', 'व्य', 'शी', 'तिः'],
    englishHint: '(It is four alphabet word)',
    sanskritHint: 'चत्वारि अक्षर शब्द',
    word: 'eightytwo',
    number: '82',
  },
  {
    jumbledWords: ['त्र्य', 'त्', 'र्य', 'शी', 'तिः', 'ति', 'शि', 'ती', 'ती:'],
    correctWord: ['त्र्य', 'शी', 'तिः'],
    englishHint: '(It is four alphabet word)',
    sanskritHint: 'चत्वारि अक्षर शब्द',
    word: 'eightythree',
    number: '83',
  },
  {
    jumbledWords: ['च', 'तु', 'तू', 'र', 'शी', 'तिः', 'ति', 'शि', 'ती', 'ती:'],
    correctWord: ['च', 'तु', 'र', 'शी', 'तिः'],
    englishHint: '(It is five alphabet word)',
    sanskritHint: 'पञ्च अक्षर शब्द',
    word: 'eightyfour',
    number: '84',
  },
  {
    jumbledWords: [
      'प',
      'ञ्चा',
      'ञ्च',
      'ञ्',
      'चा',
      'शी',
      'तिः',
      'ति',
      'शि',
      'ती',
      'ती:',
    ],
    correctWord: ['प', 'ञ्चा', 'शी', 'तिः'],
    englishHint: '(It is four alphabet word)',
    sanskritHint: 'चत्वारि अक्षर शब्द',
    word: 'eightyfive',
    number: '85',
  },
  {
    jumbledWords: ['ष', 'स', 'डा', 'ड', 'शी', 'तिः', 'ति', 'शि', 'ती', 'ती:'],
    correctWord: ['ष', 'ड', 'शी', 'तिः'],
    englishHint: '(It is four alphabet word)',
    sanskritHint: 'चत्वारि अक्षर शब्द',
    word: 'eightysix',
    number: '86',
  },
  {
    jumbledWords: [
      'स',
      'ष',
      'श',
      'प्ता',
      'प्',
      'ता',
      'शी',
      'तिः',
      'ति',
      'शि',
      'ती',
      'ती:',
    ],
    correctWord: ['स', 'प्ता', 'शी', 'तिः'],
    englishHint: '(It is four alphabet word)',
    sanskritHint: 'चत्वारि अक्षर शब्द',
    word: 'eightyseven',
    number: '87',
  },
  {
    jumbledWords: [
      'अ',
      'ष्टा',
      'ष्',
      'टा',
      'आ',
      'शी',
      'तिः',
      'ति',
      'शि',
      'ती',
      'ती:',
    ],
    correctWord: ['अ', 'ष्टा', 'शी', 'तिः'],
    englishHint: '(It is four alphabet word)',
    sanskritHint: 'चत्वारि अक्षर शब्द',
    word: 'eightyeight',
    number: '88',
  },
  {
    jumbledWords: ['न', 'वा', 'व', 'ना', 'शी', 'तिः', 'ति', 'शि', 'ती', 'ती:'],
    correctWord: ['न', 'वा', 'शी', 'तिः'],
    englishHint: '(It is four alphabet word)',
    sanskritHint: 'चत्वारि अक्षर शब्द',
    word: 'eightynine',
    number: '89',
  },
  {
    jumbledWords: ['न', 'वा', 'व', 'ना', 'तिः', 'ती', 'ती:'],
    correctWord: ['न', 'व', 'तिः'],
    englishHint: '(It is three alphabet word)',
    sanskritHint: 'त्रि अक्षर शब्द',
    word: 'ninty',
    number: '90',
  },
  {
    jumbledWords: ['ए', 'क', 'न', 'का', 'वा', 'व', 'ना', 'तिः', 'ती', 'ती:'],
    correctWord: ['ए', 'क', 'न', 'व', 'तिः'],
    englishHint: '(It is five alphabet word)',
    sanskritHint: 'पञ्च अक्षर शब्द',
    word: 'nintyone',
    number: '91',
  },
  {
    jumbledWords: [
      'द्वि',
      'द्',
      'वि',
      'न',
      'वा',
      'व',
      'ना',
      'तिः',
      'ती',
      'ती:',
    ],
    correctWord: ['द्वि', 'न', 'व', 'तिः'],
    englishHint: '(It is four alphabet word)',
    sanskritHint: 'चत्वारि अक्षर शब्द',
    word: 'nintytwo',
    number: '92',
  },
  {
    jumbledWords: [
      'त्रि',
      'त्री',
      'त्',
      'रि',
      'न',
      'वा',
      'व',
      'ना',
      'तिः',
      'ती',
      'ती:',
    ],
    correctWord: ['त्रि', 'न', 'व', 'तिः'],
    englishHint: '(It is four alphabet word)',
    sanskritHint: 'चत्वारि अक्षर शब्द',
    word: 'nintythree',
    number: '93',
  },
  {
    jumbledWords: [
      'च',
      'तू',
      'तु',
      'र्न',
      'र्',
      'न',
      'व',
      'तिः',
      'ति',
      'ती',
      'ती:',
    ],
    correctWord: ['च', 'तु', 'र्न', 'व', 'तिः'],
    englishHint: '(It is five alphabet word)',
    sanskritHint: 'पञ्च अक्षर शब्द',
    word: 'nintyfour',
    number: '94',
  },
  {
    jumbledWords: [
      'प',
      'ञ्च',
      'ञ्',
      'च',
      'न',
      'वा',
      'व',
      'ना',
      'तिः',
      'ती',
      'ती:',
    ],
    correctWord: ['प', 'ञ्च', 'न', 'व', 'तिः'],
    englishHint: '(It is five alphabet word)',
    sanskritHint: 'पञ्च अक्षर शब्द',
    word: 'nintyfive',
    number: '95',
  },
  {
    jumbledWords: ['ष', 'ण्ण', 'स', 'श', 'ण्', 'ण', 'व', 'तिः', 'ती', 'ती:'],
    correctWord: ['ष', 'ण्ण', 'व', 'तिः'],
    englishHint: '(It is four alphabet word)',
    sanskritHint: 'चत्वारि अक्षर शब्द',
    word: 'nintysix',
    number: '96',
  },
  {
    jumbledWords: [
      'स',
      'प्त',
      'प्',
      'श',
      'त',
      'न',
      'वा',
      'व',
      'ना',
      'तिः',
      'ती',
      'ती:',
    ],
    correctWord: ['स', 'प्त', 'न', 'व', 'तिः'],
    englishHint: '(It is five alphabet word)',
    sanskritHint: 'पञ्च अक्षर शब्द',
    word: 'nintyseven',
    number: '97',
  },
  {
    jumbledWords: [
      'अ',
      'आ',
      'ष्ट',
      'ष्',
      'ट',
      'न',
      'वा',
      'व',
      'ना',
      'तिः',
      'ती',
      'ती:',
    ],
    correctWord: ['अ', 'ष्ट', 'न', 'व', 'तिः'],
    englishHint: '(It is five alphabet word)',
    sanskritHint: 'पञ्च अक्षर शब्द',
    word: 'nintyeight',
    number: '98',
  },
  {
    jumbledWords: [
      'न',
      'वा',
      'व',
      'ना',
      'न',
      'वा',
      'व',
      'ना',
      'तिः',
      'ती',
      'ती:',
    ],
    correctWord: ['न', 'व', 'न', 'व', 'तिः'],
    englishHint: '(It is five alphabet word)',
    sanskritHint: 'पञ्च अक्षर शब्द',
    word: 'nintynine',
    number: '99',
  },
  {
    jumbledWords: ['स', 'ष', 'श', 'त', 'ता', 'म्', 'म', 'म्:'],
    correctWord: ['श', 'त', 'म्'],
    englishHint: '(It is three alphabet word)',
    sanskritHint: 'त्रि अक्षर शब्द',
    word: 'hundred',
    number: '100',
  },
];
