export const TestGame = [
  {
    jumbledWords: ['च', 'र्मः', 'र्', 'म्र', 'मः'],
    correctWord: ['च', 'र्मः'],
    englishHint: '(It is two alphabet word)',
    sanskritHint: 'द्वे अक्षर शब्द',
    word: 'skin',
    image: require('../../assets/body/skin.png'),
  },
  {
    jumbledWords: ['शी', 'र्ष', 'र्', 'शि', 'ष', 'म'],
    correctWord: ['शी', 'र्ष', 'म'],
    englishHint: '(It is three alphabet word)',
    sanskritHint: 'त्रि अक्षर शब्द',
    word: 'head',
    image: require('../../assets/body/head.png'),
  },
  {
    jumbledWords: ['ल', 'ला', 'ल', 'टा', 'ट', 'म्', 'म', 'म:'],
    correctWord: ['ल', 'ला', 'ट', 'म्'],
    englishHint: '(It is four alphabet word)',
    sanskritHint: 'चत्वारि अक्षर शब्द',
    word: 'forehead',
    image: require('../../assets/body/forehead.png'),
  },
  {
    jumbledWords: ['के', 'शाः', 'कै', 'क:', 'स', 'सा', 'स:'],
    correctWord: ['के', 'शाः'],
    englishHint: '(It is two alphabet word)',
    sanskritHint: 'द्वे अक्षर शब्द',
    word: 'hair',
    image: require('../../assets/body/hair.png'),
  },
  {
    jumbledWords: ['ने', 'त्र', 'त्', 'र', 'म्', 'म', 'म:', 'न', 'नें'],
    correctWord: ['ने', 'त्र', 'म्'],
    englishHint: '(It is three alphabet word)',
    sanskritHint: 'त्रि अक्षर शब्द',
    word: 'eye',
    image: require('../../assets/body/eye.png'),
  },
  {
    jumbledWords: ['भ्रूः', 'भ्', 'रूः', 'भ्:', 'भ्रू'],
    correctWord: ['भ्रूः'],
    englishHint: '(It is three alphabet word)',
    sanskritHint: 'एकम् अक्षर शब्द',
    word: 'eyebrow',
    image: require('../../assets/body/eyebrow.png'),
  },
  {
    jumbledWords: ['क', 'र्णः', 'र्', 'का:', 'णः'],
    correctWord: ['क', 'र्णः'],
    englishHint: '(It is two alphabet word)',
    sanskritHint: 'द्वे अक्षर शब्द',
    word: 'Ear',
    image: require('../../assets/body/ear.png'),
  },
  {
    jumbledWords: ['ना', 'सि', 'काः', 'न', 'स', 'का', 'सी', 'शि'],
    correctWord: ['ना', 'सि', 'काः'],
    englishHint: '(It is three alphabet word)',
    sanskritHint: 'त्रि अक्षर शब्द',
    word: 'nose',
    image: require('../../assets/body/nose.png'),
  },
  {
    jumbledWords: ['जि', 'ह्वा', 'ह्', 'जी', 'वा'],
    correctWord: ['जि', 'ह्वा'],
    englishHint: '(It is two alphabet word)',
    sanskritHint: 'द्वे अक्षर शब्द',
    word: 'tounge',
    image: require('../../assets/body/tounge.png'),
  },
  {
    jumbledWords: ['अ', 'ध', 'धा', 'र', 'रा', 'म्', 'म', 'आ'],
    correctWord: ['अ', 'ध', 'र', 'म्'],
    englishHint: '(It is four alphabet word)',
    sanskritHint: 'चत्वारि अक्षर शब्द',
    word: 'lip',
    image: require('../../assets/body/lip.png'),
  },
  {
    jumbledWords: ['मु', 'मू', 'ख', 'ख:', 'म्', 'म', 'म:'],
    correctWord: ['मु', 'ख', 'म्'],
    englishHint: '(It is three alphabet word)',
    sanskritHint: 'त्रि अक्षर शब्द',
    word: 'Mouth',
    image: require('../../assets/body/mouth.png'),
  },
  {
    jumbledWords: ['कू', 'र्च', 'म्', 'म', 'म:', 'कु', 'र्', 'च'],
    correctWord: ['कू', 'र्च', 'म्'],
    englishHint: '(It is three alphabet word)',
    sanskritHint: 'त्रि अक्षर शब्द',
    word: 'beard',
    image: require('../../assets/body/beard.png'),
  },
  {
    jumbledWords: ['श्म', 'श्', 'म:', 'श्रुः', 'श्', 'रुः'],
    correctWord: ['श्म', 'श्रुः'],
    englishHint: '(It is two alphabet word)',
    sanskritHint: 'द्वे अक्षर शब्द',
    word: 'moustach',
    image: require('../../assets/body/moustach.png'),
  },
  {
    jumbledWords: ['क', 'का', 'पो', 'पौ', 'लः', 'ल'],
    correctWord: ['क', 'पो', 'लः'],
    englishHint: '(It is three alphabet word)',
    sanskritHint: 'त्रि अक्षर शब्द',
    word: 'cheek',
    image: require('../../assets/body/cheek.png'),
  },
  {
    jumbledWords: ['चि', 'ची', 'बू', 'बु', 'क', 'म्', 'म', 'म:'],
    correctWord: ['चि', 'बु', 'क', 'म्'],
    englishHint: '(It is four alphabet word)',
    sanskritHint: 'चत्वारि अक्षर शब्द',
    word: 'chin',
    image: require('../../assets/body/chin.png'),
  },
  {
    jumbledWords: ['द', 'दा', 'न्तः', 'न्', 'तः'],
    correctWord: ['द', 'न्तः'],
    englishHint: '(It is two alphabet word)',
    sanskritHint: 'द्वे अक्षर शब्द',
    word: 'teeth',
    image: require('../../assets/body/teeth.png'),
  },
  {
    jumbledWords: ['ग्री', 'वाः'],
    correctWord: ['ग्री', 'ग्', 'री', 'वाः', 'व:'],
    englishHint: '(It is two alphabet word)',
    sanskritHint: 'द्वे अक्षर शब्द',
    word: 'neck',
    image: require('../../assets/body/neck.png'),
  },
  {
    jumbledWords: ['स्क', 'स्', 'क', 'न्धः', 'न्', 'धः'],
    correctWord: ['स्क', 'न्धः'],
    englishHint: '(It is two alphabet word)',
    sanskritHint: 'द्वे अक्षर शब्द',
    word: 'shoulder',
    image: require('../../assets/body/shoulder.png'),
  },
  {
    jumbledWords: ['उ', 'ऊ', 'रः', 'र', 'रा'],
    correctWord: ['उ', 'रः'],
    englishHint: '(It is two alphabet word)',
    sanskritHint: 'द्वे अक्षर शब्द',
    word: 'chest',
    image: require('../../assets/body/chest.png'),
  },
  {
    jumbledWords: ['भु', 'जः', 'भू', 'भ', 'ज', 'जा:'],
    correctWord: ['भु', 'जः'],
    englishHint: '(It is two alphabet word)',
    sanskritHint: 'द्वे अक्षर शब्द',
    word: 'arm',
    image: require('../../assets/body/arm.png'),
  },
  {
    jumbledWords: ['कू', 'कु', 'र्प', 'रः'],
    correctWord: ['कू', 'र्प', 'र्', 'प', 'रः'],
    englishHint: '(It is three alphabet word)',
    sanskritHint: 'त्रि अक्षर शब्द',
    word: 'elbow',
    image: require('../../assets/body/elbow.png'),
  },
  {
    jumbledWords: ['उ', 'ऊ', 'दा', 'द', 'र', 'म्', 'म', 'म:'],
    correctWord: ['उ', 'द', 'र', 'म्'],
    englishHint: '(It is four alphabet word)',
    sanskritHint: 'चत्वारि अक्षर शब्द',
    word: 'stomach',
    image: require('../../assets/body/stomach.png'),
  },
  {
    jumbledWords: ['ना', 'न', 'ना:', 'न:', 'भिः', 'भी:', 'भी'],
    correctWord: ['ना', 'भिः'],
    englishHint: '(It is two alphabet word)',
    sanskritHint: 'द्वे अक्षर शब्द',
    word: 'navel',
    image: require('../../assets/body/navel.png'),
  },
  {
    jumbledWords: ['क', 'का', 'टिः', 'टी:', 'टी'],
    correctWord: ['क', 'टिः'],
    englishHint: '(It is two alphabet word)',
    sanskritHint: 'द्वे अक्षर शब्द',
    word: 'hip',
    image: require('../../assets/body/hip.png'),
  },
  {
    jumbledWords: ['म', 'णि', 'ण', 'ब', 'न्धः', 'न्', 'धः', 'णी'],
    correctWord: ['म', 'णि', 'ब', 'न्धः'],
    englishHint: '(It is four alphabet word)',
    sanskritHint: 'चत्वारि अक्षर शब्द',
    word: 'wrist',
    image: require('../../assets/body/wrist.png'),
  },
  {
    jumbledWords: ['क', 'का', 'र', 'त', 'ल', 'म्', 'म', 'म:'],
    correctWord: ['क', 'र', 'त', 'ल', 'म्'],
    englishHint: '(It is four alphabet word)',
    sanskritHint: 'पञ्च अक्षर शब्द',
    word: 'palm',
    image: require('../../assets/body/palm.png'),
  },
  {
    jumbledWords: ['अं', 'गु', 'लिः', 'गू', 'ली', 'ली:'],
    correctWord: ['अं', 'गु', 'लिः'],
    englishHint: '(It is three alphabet word)',
    sanskritHint: 'त्रि अक्षर शब्द',
    word: 'finger',
    image: require('../../assets/body/finger.png'),
  },
  {
    jumbledWords: ['न', 'खः', 'ख', 'ना'],
    correctWord: ['न', 'खः'],
    englishHint: '(It is two alphabet word)',
    sanskritHint: 'द्वे अक्षर शब्द',
    word: 'nail',
    image: require('../../assets/body/nail.png'),
  },
  {
    jumbledWords: ['अं', 'अ', 'गु', 'गू', 'ष्ठः', 'ष्', 'ठः'],
    correctWord: ['अं', 'गु', 'ष्ठः'],
    englishHint: '(It is three alphabet word)',
    sanskritHint: 'त्रि अक्षर शब्द',
    word: 'thumb',
    image: require('../../assets/body/thumb.png'),
  },
  {
    jumbledWords: ['जं', 'ज', 'घा', 'घ', 'घा:', 'घ:'],
    correctWord: ['जं', 'घा'],
    englishHint: '(It is two alphabet word)',
    sanskritHint: 'द्वे अक्षर शब्द',
    word: 'thigh',
    image: require('../../assets/body/thigh.png'),
  },
  {
    jumbledWords: ['जा', 'ज', 'नुः', 'नु', 'नू', 'नू:'],
    correctWord: ['जा', 'नुः'],
    englishHint: '(It is two alphabet word)',
    sanskritHint: 'द्वे अक्षर शब्द',
    word: 'knee',
    image: require('../../assets/body/knee.png'),
  },
  {
    jumbledWords: ['च', 'र', 'णः', 'ण', 'न:', 'चा'],
    correctWord: ['च', 'र', 'णः'],
    englishHint: '(It is three alphabet word)',
    sanskritHint: 'त्रि अक्षर शब्द',
    word: 'leg',
    image: require('../../assets/body/leg.png'),
  },
  {
    jumbledWords: ['गु', 'गू', 'ग', 'ल्फः', 'ल्', 'फः'],
    correctWord: ['गु', 'ल्फः'],
    englishHint: '(It is three alphabet word)',
    sanskritHint: 'त्रि अक्षर शब्द',
    word: 'ankle',
    image: require('../../assets/body/ankle.png'),
  },
  {
    jumbledWords: ['ए', 'डु', 'क', 'म्', 'डू', 'म', 'म:'],
    correctWord: ['ए', 'डु', 'क', 'म्'],
    englishHint: '(It is four alphabet word)',
    sanskritHint: 'चत्वारि अक्षर शब्द',
    word: 'heal',
    image: require('../../assets/body/heal.png'),
  },
  {
    jumbledWords: ['पा', 'प', 'दां', 'दा', 'गू', 'गु', 'ष्ठः', 'ष्', 'ठः'],
    correctWord: ['पा', 'दां', 'गु', 'ष्ठः'],
    englishHint: '(It is four alphabet word)',
    sanskritHint: 'चत्वारि अक्षर शब्द',
    word: 'toe',
    image: require('../../assets/body/toe.png'),
  },
  {
    jumbledWords: ['पा', 'प', , 'दः', 'द', 'दा', 'दा:'],
    correctWord: ['पा', 'दः'],
    englishHint: '(It is two alphabet word)',
    sanskritHint: 'द्वे अक्षर शब्द',
    word: 'feet',
    image: require('../../assets/body/feet.png'),
  },
];
