export const VegetableGame = [
  {
    jumbledWords: ['टिं', 'टि', 'डी', 'ड', 'श:', 'श', 'ष:', 'स:'],
    correctWord: ['टिं', 'डी', 'श:'],
    englishHint: '(It is three alphabet word)',
    sanskritHint: 'त्रि अक्षर शब्द',
    word: 'AppleGourd',
    image: require('../../assets/vegetables/Applegourd.png'),
  },
  {
    jumbledWords: ['का', 'क', 'र', 'वे', 'व', 'ल्लः', 'ल् ', 'लः'],
    correctWord: ['का', 'र', 'वे', 'ल्लः'],
    englishHint: '(It is four alphabet word)',
    sanskritHint: 'चत्वारि अक्षर शब्द',
    word: 'BitterGourd',
    image: require('../../assets/vegetables/BitterGourd.png'),
  },
  {
    jumbledWords: ['वृ', 'व', 'न्ता', 'न्', 'ता', 'कः'],
    correctWord: ['वृ', 'न्ता', 'कः'],
    englishHint: '(It is three alphabet word)',
    sanskritHint: 'त्रि अक्षर शब्द',
    word: 'Brinjal',
    image: require('../../assets/vegetables/Brinjal.png'),
  },
  {
    jumbledWords: ['क', 'का', 'पि', 'पी', 'शा', 'सा', 'क', 'म्', 'म'],
    correctWord: ['क', 'पि', 'शा', 'क', 'म्'],
    englishHint: '(It is five alphabet word)',
    sanskritHint: 'पञ्च अक्षर शब्द',
    word: 'Broccoli',
    image: require('../../assets/vegetables/Broccoli.png'),
  },
  {
    jumbledWords: ['क', 'का', 'पि', 'पी', 'शा', 'सा', 'क'],
    correctWord: ['क', 'पि', 'शा', 'क'],
    englishHint: '(It is four alphabet word)',
    sanskritHint: 'चत्वारि अक्षर शब्द',
    word: 'Cabbage',
    image: require('../../assets/vegetables/Cabbage.png'),
  },
  {
    jumbledWords: ['म', 'हा', 'ह', 'म', 'रि', 'री', 'चि', 'ची', 'का', 'क'],
    correctWord: ['म', 'हा', 'म', 'री', 'चि', 'का'],
    englishHint: '(It is six alphabet word)',
    sanskritHint: 'षट् अक्षर शब्द',
    word: 'Capsicum',
    image: require('../../assets/vegetables/Capsicum.png'),
  },
  {
    jumbledWords: ['गो', 'ग', 'जि', 'ह्वा', 'ह्व', 'ह्', ' जी'],
    correctWord: ['गो', 'जि', 'ह्वा'],
    englishHint: '(It is three alphabet word)',
    sanskritHint: 'त्रि अक्षर शब्द',
    word: 'cauliflower',
    image: require('../../assets/vegetables/cauliflower.png'),
  },
  {
    jumbledWords: ['च', 'ण', 'चा', 'न', 'क', 'का'],
    correctWord: ['च', 'ण', 'क'],
    englishHint: '(It is three alphabet word)',
    sanskritHint: 'त्रि अक्षर शब्द',
    word: 'Chickpea',
    image: require('../../assets/vegetables/Chickpea.png'),
  },
  {
    jumbledWords: ['म', 'री', 'र', 'रि ', 'चं', 'च'],
    correctWord: ['म', 'री', 'चं'],
    englishHint: '(It is three alphabet word)',
    sanskritHint: 'त्रि अक्षर शब्द',
    word: 'Chilli',
    image: require('../../assets/vegetables/Chilli.png'),
  },
  {
    jumbledWords: ['धा', 'ध', 'न्या', 'न्', 'या', 'क', 'म्', 'म'],
    correctWord: ['धा', 'न्या', 'क', 'म्'],
    englishHint: '(It is four alphabet word)',
    sanskritHint: 'चत्वारि अक्षर शब्द',
    word: 'Coriander',
    image: require('../../assets/vegetables/Coriander.png'),
  },
  {
    jumbledWords: ['ल', 'शु', 'श', 'नं', 'न', 'सू', 'सु'],
    correctWord: ['ल', 'शु', 'नं'],
    englishHint: '(It is three alphabet word)',
    sanskritHint: 'त्रि अक्षर शब्द',
    word: 'Garlic',
    image: require('../../assets/vegetables/Garlic.png'),
  },
  {
    jumbledWords: ['आ', 'अ', 'द्र', 'द्', 'क', 'म्', 'म'],
    correctWord: ['आ', 'द्र', 'क', 'म्'],
    englishHint: '(It is four alphabet word)',
    sanskritHint: 'चत्वारि अक्षर शब्द',
    word: 'Ginger',
    image: require('../../assets/vegetables/Ginger.png'),
  },
  {
    jumbledWords: ['अ', 'ला', 'ल', 'बु', 'बू', 'ब'],
    correctWord: ['अ', 'ला', 'बु'],
    englishHint: '(It is three alphabet word)',
    sanskritHint: 'त्रि अक्षर शब्द',
    word: 'Gourd',
    image: require('../../assets/vegetables/Gourd.png'),
  },
  {
    jumbledWords: ['ह', 'री', 'रि', 'र', 'त', 'शि', 'श', 'बि', 'ब', 'बी', 'का'],
    correctWord: ['ह', 'रि', 'त', 'शि', 'बि', 'का'],
    englishHint: '(It is six alphabet word)',
    sanskritHint: 'षट् अक्षर शब्द',
    word: 'GreenBean',
    image: require('../../assets/vegetables/GreenBean.png'),
  },
  {
    jumbledWords: ['ह', 'री', 'रि', 'र', 'त', 'म', 'री', 'रि', 'चं', 'च'],
    correctWord: ['ह', 'रि', 'त', 'म', 'री', 'चं'],
    englishHint: '(It is six alphabet word)',
    sanskritHint: 'षट् अक्षर शब्द',
    word: 'GreenChilli',
    image: require('../../assets/vegetables/GreenChilli.png'),
  },
  {
    jumbledWords: ['ह', 'री', 'रि', 'र', 'त', 'प', 'ला', 'ण्डुः', 'ण्', 'डुः'],
    correctWord: ['ह', 'रि', 'त', 'प', 'ला', 'ण्डुः'],
    englishHint: '(It is six alphabet word)',
    sanskritHint: 'षट् अक्षर शब्द',
    word: 'GreenOnion',
    image: require('../../assets/vegetables/GreenOnion.png'),
  },
  {
    jumbledWords: ['भि', 'ण्', 'डि', 'का', 'क', 'भी'],
    correctWord: ['भि', 'ण्डि', 'का'],
    englishHint: '(It is three alphabet word)',
    sanskritHint: 'त्रि अक्षर शब्द',
    word: 'Ladyfinger',
    image: require('../../assets/vegetables/Ladyfinger.png'),
  },
  {
    jumbledWords: ['पा', 'प', 'ल', 'घ्न', 'घ्', 'न'],
    correctWord: ['पा', 'ल', 'घ्न'],
    englishHint: '(It is three alphabet word)',
    sanskritHint: 'त्रि अक्षर शब्द',
    word: 'Mushroom',
    image: require('../../assets/vegetables/Mushroom.png'),
  },
  {
    jumbledWords: ['स', 'र्श', 'र्', 'श', 'पः', 'पः'],
    correctWord: ['स', 'र्श', 'पः'],
    englishHint: '(It is three alphabet word)',
    sanskritHint: 'त्रि अक्षर शब्द',
    word: 'Mustard',
    image: require('../../assets/vegetables/Mustard.png'),
  },
  {
    jumbledWords: ['प', 'ला', 'ल', 'ण्डुः', 'ण्', 'डुः'],
    correctWord: ['प', 'ला', 'ण्डुः'],
    englishHint: '(It is three alphabet word)',
    sanskritHint: 'त्रि अक्षर शब्द',
    word: 'Onion',
    image: require('../../assets/vegetables/Onion.png'),
  },
  {
    jumbledWords: ['क', 'ला', 'ल', 'यः', 'य', 'का'],
    correctWord: ['क', 'ला', 'यः'],
    englishHint: '(It is three alphabet word)',
    sanskritHint: 'त्रि अक्षर शब्द',
    word: 'Peas',
    image: require('../../assets/vegetables/Peas.png'),
  },
  {
    jumbledWords: ['अ', 'आ', 'ज', 'गं', 'ग', 'ध:', 'ध'],
    correctWord: ['अ', 'ज', 'गं', 'ध:'],
    englishHint: '(It is four alphabet word)',
    sanskritHint: 'चत्वारि अक्षर शब्द',
    word: 'Peppermint',
    image: require('../../assets/vegetables/Peppermint.png'),
  },
  {
    jumbledWords: ['प', 'टो', 'ट', 'लः', 'ल', 'तौ'],
    correctWord: ['प', 'टो', 'लः'],
    englishHint: '(It is three alphabet word)',
    sanskritHint: 'त्रि अक्षर शब्द',
    word: 'PointedGourd',
    image: require('../../assets/vegetables/PointedGourd.png'),
  },
  {
    jumbledWords: ['आ', 'लु', 'कः', 'अ', 'ल', 'क'],
    correctWord: ['आ', 'लु', 'कः'],
    englishHint: '(It is three alphabet word)',
    sanskritHint: 'त्रि अक्षर शब्द',
    word: 'Potato',
    image: require('../../assets/vegetables/Potato.png'),
  },
  {
    jumbledWords: ['कु', 'क', 'ष', 'मां', 'मा', 'स', 'ड'],
    correctWord: ['कु', 'ष', 'मां', 'ड'],
    englishHint: '(It is four alphabet word)',
    sanskritHint: 'चत्वारि अक्षर शब्द',
    word: 'Pumpkin',
    image: require('../../assets/vegetables/Pumpkin.png'),
  },
  {
    jumbledWords: ['को', 'क', 'शा', 'श', 'त', 'की', 'क'],
    correctWord: ['को', 'शा', 'त', 'की'],
    englishHint: '(It is four alphabet word)',
    sanskritHint: 'चत्वारि अक्षर शब्द',
    word: 'RidgeGourd',
    image: require('../../assets/vegetables/RidgeGourd.png'),
  },
  {
    jumbledWords: ['अ', 'ग्नि', 'ग्न', 'शा', 'खा', 'ख', 'सा'],
    correctWord: ['अ', 'ग्नि', 'शा', 'खा'],
    englishHint: '(It is four alphabet word)',
    sanskritHint: 'चत्वारि अक्षर शब्द',
    word: 'Saffron',
    image: require('../../assets/vegetables/Saffron.png'),
  },
  {
    jumbledWords: ['पा', 'प', 'ल', 'कः', 'क', 'ली'],
    correctWord: ['पा', 'ल', 'कः'],
    englishHint: '(It is three alphabet word)',
    sanskritHint: 'त्रि अक्षर शब्द',
    word: 'Spinach',
    image: require('../../assets/vegetables/Spinach.png'),
  },
  {
    jumbledWords: ['जा', 'ज', 'लि', 'लि', 'नी', 'नि'],
    correctWord: ['जा', 'लि', 'नी'],
    englishHint: '(It is three alphabet word)',
    sanskritHint: 'त्रि अक्षर शब्द',
    word: 'SpongeGourd',
    image: require('../../assets/vegetables/SpongeGourd.png'),
  },
  {
    jumbledWords: ['पा', 'प', 'ल', 'ङ्क', 'ङ्', 'क', 'ङ'],
    correctWord: ['पा', 'ल', 'ङ्क'],
    englishHint: '(It is three alphabet word)',
    sanskritHint: 'त्रि अक्षर शब्द',
    word: 'SugarBeets',
    image: require('../../assets/vegetables/SugarBeets.png'),
  },
  {
    jumbledWords: ['कु', 'न्द', 'रू:', 'कु', 'न्', 'द', 'रू'],
    correctWord: ['कु', 'न्द', 'रू:'],
    englishHint: '(It is three alphabet word)',
    sanskritHint: 'त्रि अक्षर शब्द',
    word: 'Tendli',
    image: require('../../assets/vegetables/Tendli.png'),
  },
];
