export const ZeroTo20 = [
  {text: '0 शून्य shunya', seachText: 'शून्य'},
  {text: '1 एकम् ekam', seachText: 'ekam'},
  {text: '2 द्वे dve', seachText: 'द्वे'},
  {text: '3 त्रीणि treeni', seachText: 'त्रीणि'},
  {text: '4 चत्वारि chatvaari', seachText: 'चत्वारि'},
  {text: '5 पञ्च pancha', seachText: 'pancha'},
  {text: '6 षट् shat', seachText: 'shat'},
  {text: '7 सप्त sapta', seachText: 'सप्त'},
  {text: '8 अष्ट ashta', seachText: 'अष्ट'},
  {text: '9 नव nava', seachText: 'नव'},
  {text: '10 दश dasha', seachText: 'दश'},
  {text: '11 एकादश ekaadasha', seachText: 'एकादश'},
  {text: '12 द्वादश dvaadasha3', seachText: 'द्वादश'},
  {text: '13 त्रयोदश trayodasha', seachText: 'त्रयोदश'},
  {text: '14 चतुर्दश chaturdasha', seachText: 'चतुर्दश'},
  {text: '15 पञ्चदश panchadasha', seachText: 'पञ्चदश'},
  {text: '16 षोडश shodash', seachText: 'षोडश'},
  {text: '17 सप्तदश saptadasha', seachText: 'सप्तदश'},
  {text: '18 अष्टादश ashtaadasha', seachText: 'अष्टादश'},
  {text: '19 नवदश navadasha', seachText: 'नवदश'},
  {text: '20 विंशतिः vimshatihi', seachText: 'विंशतिः'},
];
