export const TwentyOneTo40 = [
  {text: '21 एकविंशतिः ekavimshatihi', seachText: 'एकविंशतिः'},
  {text: '22 द्वाविंशतिः dvaavimshathi', seachText: 'द्वाविंशतिः'},
  {text: '23 त्रयोविंशतिः trayovimshatihi', seachText: 'त्रयोविंशतिः'},
  {text: '24 चतुर्विंशतिः chaturvimshatihi', seachText: 'चतुर्विंशतिः'},
  {text: '25 पञ्चविंशतिः panchavimshatihi', seachText: 'पञ्चविंशतिः'},
  {text: '26 षड्विंशतिः shadvimshatihi', seachText: 'षड्विंशतिः'},
  {text: '27 सप्तविंशतिः saptavimshatihi', seachText: 'सप्तविंशतिः'},
  {text: '28 अष्टाविंशतिः ashtaavimshatihi', seachText: 'अष्टाविंशतिः'},
  {text: '29 नवविंशतिः navavimshatihi', seachText: 'नवविंशतिः'},
  {text: '30 त्रिंशत् trimshat', seachText: 'trimshat'},
  {text: '31 एकत्रिंशत् ekatrimshat', seachText: 'ekatrimshat'},
  {text: '32 द्वात्रिंशत् dvaatrimshat', seachText: 'dvaatrimshat'},
  {text: '33 त्रयस्त्रिंशत् trayastrimshat', seachText: 'trayastrimshat'},
  {text: '34 चतुस्त्रिंशत् chatustrimshat', seachText: 'chatustrimshat'},
  {text: '35 पञ्चत्रिंशत् panchatrimshat', seachText: 'panchatrimshat'},
  {text: '36 षट्त्रिंशत् shat-trimshat', seachText: 'shat-trimshat'},
  {text: '37 सप्तत्रिंशत् saptatrimshat', seachText: 'saptatrimshat'},
  {text: '38 अष्टत्रिंशत् ashtatrimshat', seachText: 'ashtatrimshat'},
  {text: '39 नवत्रिंशत् navatrimshat', seachText: 'navatrimshat'},
  {text: '40 चत्वारिंशत् chatvaarimshat', seachText: 'chatvaarimshat'},
];
