export const SixtyOneTo80 = [
  {text: '61 एकषष्टिः ekashashtihi', seachText: 'एकषष्टिः'},
  {text: '62 द्विषष्टिः dvishashtihi', seachText: 'द्विषष्टिः'},
  {text: '63 त्रिषष्टिः trishashtihi', seachText: 'त्रिषष्टिः'},
  {text: '64 चतुःषष्टिः chatuhushashtihi', seachText: 'चतुःषष्टिः'},
  {text: '65 पञ्चषष्टिः panchashashtihi', seachText: 'पञ्चषष्टिः'},
  {text: '66 षट्षष्टिः shatshashtihi', seachText: 'षट्षष्टिः'},
  {text: '67 सप्तषष्टिः saptashashtihi', seachText: 'सप्तषष्टिः'},
  {text: '68 अष्टषष्टिः ashtashashtihi', seachText: 'अष्टषष्टिः'},
  {text: '69 नवषष्टिः navashashtihi', seachText: 'नवषष्टिः'},
  {text: '70 सप्ततिः saptatihi', seachText: 'सप्ततिः'},
  {text: '71 एकसप्ततिः ekasaptatihi', seachText: 'एकसप्ततिः'},
  {text: '72 द्विसप्ततिः dvisaptatihi', seachText: 'द्विसप्ततिः'},
  {text: '73 त्रिसप्ततिः trisaptatihi', seachText: 'त्रिसप्ततिः'},
  {text: '74 चतुःसप्ततिः chatuhusaptatihi', seachText: 'चतुःसप्ततिः'},
  {text: '75 पञ्चसप्ततिः panchasaptatihi', seachText: 'पञ्चसप्ततिः'},
  {text: '76 षट्सप्ततिः shatsaptatihi', seachText: 'षट्सप्ततिः'},
  {text: '77 सप्तसप्ततिः saptasaptatihi', seachText: 'सप्तसप्ततिः'},
  {text: '78 अष्टसप्ततिः ashtasaptatihi', seachText: 'अष्टसप्ततिः'},
  {text: '79 नवसप्ततिः navasaptatihi', seachText: 'नवसप्ततिः'},
  {text: '80 अशीतिः asheetihi', seachText: 'अशीतिः'},
];
