export const EightyOneTo100 = [
  {text: '81 एकाशीतिः ekaasheetihi', seachText: 'एकाशीतिः'},
  {text: '82 द्व्यशीतिः dvyasheetihi', seachText: 'द्व्यशीतिः'},
  {text: '83 त्र्यशीतिः tryasheetihi', seachText: 'त्र्यशीतिः'},
  {text: '84 चतुरशीतिः chaturasheetihi', seachText: 'चतुरशीतिः'},
  {text: '85 पञ्चाशीतिः panchaasheetihi', seachText: 'पञ्चाशीतिः'},
  {text: '86 षडशीतिः shadasheetihi', seachText: 'षडशीतिः'},
  {text: '87 सप्ताशीतिः saptaasheetihi', seachText: 'सप्ताशीतिः'},
  {text: '88 अष्टाशीतिः ashtaasheetihi', seachText: 'अष्टाशीतिः'},
  {text: '89 नवाशीतिः navaasheetihi', seachText: 'नवाशीतिः'},
  {text: '90 नवतिः navatihi', seachText: 'नवतिः'},
  {text: '91 एकनवतिः ekanavatihi', seachText: 'एकनवतिः'},
  {text: '92 द्विनवतिः dvinavatihi', seachText: 'द्विनवतिः'},
  {text: '93 त्रिनवतिः trinavatihi', seachText: 'त्रिनवतिः'},
  {text: '94 चतुर्नवतिः chaturnavatihi', seachText: 'चतुर्नवतिः'},
  {text: '95 पञ्चनवतिः panchanavatihi', seachText: 'पञ्चनवतिः'},
  {text: '96 षण्णवतिः shannavatihi', seachText: 'षण्णवतिः'},
  {text: '97 सप्तनवतिः saptanavatihi', seachText: 'सप्तनवतिः'},
  {text: '98 अष्टनवतिः ashtanavatihi', seachText: 'अष्टनवतिः'},
  {text: '99 नवनवतिः navanavatihi', seachText: 'नवनवतिः'},
  {text: '100 शतम् shatam', seachText: 'shatam'},
];
